#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6"]
# ///
"""Build, validate, and sync the Strata feature map."""

from __future__ import annotations

import argparse
import functools
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SECTIONS = ("Summary", "Behavior", "Design", "History", "Known gaps")
STATUSES = ("proposed", "in-progress", "shipped", "deprecated", "removed")
REVIEWS = ("draft", "reviewed")
TYPES = ("feat", "fix", "perf", "refactor", "docs", "test", "build", "ci", "chore", "revert", "style")
REQUIRED = ("title", "status", "origin", "branch", "reviewed_at", "review", "code", "tests")
OPTIONAL = ("docs", "related")
LIST_FIELDS = ("code", "tests", "docs", "related")
MAX_DEPTH = 4
REF = r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+#\d+"
CITED_RE = re.compile(rf"\s{REF}(?:,\s*{REF})*(?:\s\(unverified\))?$")
SHA_RE = re.compile(r"[0-9a-f]{40}")
DATE_RE = re.compile(r"\d{4}-\d{2}-\d{2}")
TITLE_RE = re.compile(r"^(\w+)(?:\(([^)]*)\))?(!)?:\s*(.*)$")
PR_SUBJECT_RE = re.compile(r"\(#(\d+)\)$|^Merge pull request #(\d+)")
HISTORY_HEADER = ["Date", "PR", "Type", "Change"]
GENERATED = "<!-- Generated by scripts/featuremap.py index. Do not edit. -->"
SWEEP_SECTIONS = ("Scope", "Setup", "Probes", "Hand-offs")
SWEEP_REQUIRED = ("title", "reviewed_at")
SWEEP_OPTIONAL = ("triggers", "tools")
HANDOFF_RE = re.compile(r"^(.+?)\s*→\s*`([a-z][a-z0-9-]*)`\.?$")
E2E_PREFIX = "tests/e2e/"
TIERS = {1: "family", 2: "related", 3: "inbound related"}


@dataclass(frozen=True)
class Issue:
    level: str
    where: str
    message: str

    def __str__(self) -> str:
        return f"{self.level}: {self.where}: {self.message}"


@dataclass
class Node:
    id: str
    path: str
    meta: dict
    sections: dict[str, str]
    behavior: list[str] = field(default_factory=list)
    history: list[dict] = field(default_factory=list)

    @property
    def depth(self) -> int:
        return self.id.count("/") + 1

    def listed(self, key: str) -> list[str]:
        value = self.meta.get(key)
        return [v for v in value if isinstance(v, str)] if isinstance(value, list) else []

    def patterns(self) -> list[str]:
        return self.listed("code") + self.listed("tests")

    def reviewed_at(self) -> str | None:
        sha = self.meta.get("reviewed_at")
        return sha if isinstance(sha, str) and SHA_RE.fullmatch(sha) else None


@dataclass
class Tree:
    root: Path
    nodes: dict[str, Node]
    issues: list[Issue]

    def ordered(self) -> list[str]:
        return sorted(self.nodes, key=id_key)

    def subtree(self, node_id: str) -> list[str]:
        return [n for n in self.ordered() if n == node_id or n.startswith(node_id + "/")]

    def children(self, node_id: str) -> list[str]:
        return [n for n in self.subtree(node_id) if n.count("/") == node_id.count("/") + 1]

    def ancestors(self, node_id: str) -> list[str]:
        parts = node_id.split("/")
        candidates = ("/".join(parts[:i]) for i in range(2, len(parts)))
        return [c for c in candidates if c in self.nodes]


@dataclass
class Scopes:
    mapping: dict[str, str | None]
    ignore: set[str]
    fallback: set[str] = field(default_factory=set)


@dataclass
class Assignment:
    node: str | None
    reason: str
    affected: list[str]


@dataclass
class Sweep:
    """One QA sweep: `qa/sweeps/<area>.md`, owning every node under `features/<area>/`."""

    area: str
    path: str
    meta: dict
    sections: dict[str, str]
    probes: dict[str | None, list[str]] = field(default_factory=dict)
    handoffs: list[tuple[str, str]] = field(default_factory=list)

    def listed(self, key: str) -> list[str]:
        value = self.meta.get(key)
        return [v for v in value if isinstance(v, str)] if isinstance(value, list) else []

    def reviewed_at(self) -> str | None:
        sha = self.meta.get("reviewed_at")
        return sha if isinstance(sha, str) and SHA_RE.fullmatch(sha) else None


@dataclass
class Sweeps:
    sweeps: dict[str, Sweep]
    issues: list[Issue]

    def owner(self, node_id: str) -> str | None:
        area = node_id.split("/")[0]
        return area if area in self.sweeps else None


@dataclass
class Radius:
    """Nodes a change reaches: primary nodes, then tiers 1 (family), 2 (related), 3 (inbound related)."""

    primary: list[str]
    hits: dict[str, int]
    owner: str | None
    tiers: dict[int, list[str]]
    why: dict[str, str]
    forced: dict[str, list[str]]
    unmapped: list[str]

    def nodes(self, upto: int) -> list[str]:
        return self.primary + [n for t in range(1, upto + 1) for n in self.tiers.get(t, [])]

    def tier_of(self, node_id: str) -> int | None:
        if node_id in self.primary:
            return 0
        return next((t for t, ids in self.tiers.items() if node_id in ids), None)


@dataclass
class PlanInput:
    subject: str
    head: str | None
    pr: dict | None
    files: list[str]
    radius: Radius | None
    areas: list[str]
    tier: int


def id_key(node_id: str) -> list[str]:
    return node_id.split("/")


def load_yaml(path: Path) -> dict:
    data = yaml.safe_load(path.read_text()) if path.exists() else None
    return data if isinstance(data, dict) else {}


def load_sources(root: Path) -> dict:
    return load_yaml(root / "sources.yaml")


def load_scopes(root: Path) -> Scopes:
    data = load_yaml(root / "scopes.yaml")
    mapping = {str(k): v for k, v in (data.get("scopes") or {}).items()}
    fallback = {str(n) for n in data.get("fallback") or []}
    return Scopes(mapping, {str(s) for s in data.get("ignore") or []}, fallback)


def load_dataset(root: Path) -> dict[int, dict]:
    path = root / "data" / "prs.jsonl"
    if not path.exists():
        return {}
    rows = (json.loads(line) for line in path.read_text().splitlines() if line.strip())
    return {row["number"]: row for row in rows}


def save_dataset(root: Path, rows: dict[int, dict]) -> None:
    path = root / "data" / "prs.jsonl"
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = (json.dumps(rows[n], ensure_ascii=False, sort_keys=True) + "\n" for n in sorted(rows))
    path.write_text("".join(lines))


@functools.lru_cache(maxsize=None)
def glob_regex(pattern: str) -> re.Pattern:
    """`*` stays within a directory, `**` crosses them; a plain path also matches what is under it."""
    if not any(c in pattern for c in "*?"):
        return re.compile(re.escape(pattern.rstrip("/")) + r"(?:/.*)?")
    out, i = [], 0
    while i < len(pattern):
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
        elif pattern.startswith("**", i):
            out.append(".*")
            i += 2
        elif pattern[i] == "*":
            out.append("[^/]*")
            i += 1
        elif pattern[i] == "?":
            out.append("[^/]")
            i += 1
        else:
            out.append(re.escape(pattern[i]))
            i += 1
    return re.compile("".join(out))


def matches(pattern: str, path: str) -> bool:
    return glob_regex(pattern).fullmatch(path) is not None


def parse_title(title: str) -> tuple[str | None, str | None, bool, str]:
    m = TITLE_RE.match(title)
    if not m:
        return None, None, False, title
    return m.group(1), m.group(2) or None, bool(m.group(3)), m.group(4)


# Parsing


def load_tree(root: Path) -> Tree:
    features = root / "features"
    tree = Tree(root, {}, [])
    if not features.is_dir():
        tree.issues.append(Issue("error", "features/", "directory is missing"))
        return tree
    for path in sorted(features.rglob("*")):
        parts = path.relative_to(features).parts
        rel = path.relative_to(root).as_posix()
        if any(p.startswith(".") for p in parts):
            continue
        if path.is_dir():
            if len(parts) >= 2 and not (path / "index.md").is_file():
                tree.issues.append(Issue("error", rel, "directory without index.md"))
            if len(parts) >= 2 and path.with_name(path.name + ".md").exists():
                tree.issues.append(Issue("error", rel, f"{path.name}.md and {path.name}/ both define one id"))
            continue
        if path.suffix != ".md":
            tree.issues.append(Issue("error", rel, "only Markdown files belong under features/"))
            continue
        if len(parts) == 1:
            tree.issues.append(Issue("error", rel, "areas are directories; no files directly under features/"))
            continue
        if len(parts) == 2 and parts[1] == "index.md":
            tree.issues.append(Issue("error", rel, "areas are directories only; an area has no index.md"))
            continue
        node_id = "/".join(parts[:-1]) if parts[-1] == "index.md" else "/".join(parts)[: -len(".md")]
        if node_id in tree.nodes:
            continue
        node, problems = parse_node(node_id, rel, path.read_text())
        tree.nodes[node_id] = node
        tree.issues.extend(Issue("error", rel, p) for p in problems)
        if node.depth > MAX_DEPTH:
            tree.issues.append(Issue("warning", rel, "deeper than area, feature, child, grandchild"))
    return tree


def parse_front_matter(text: str) -> tuple[dict | None, str, list[str]]:
    """Returns (meta, body, problems); meta is None when the file has no front matter."""
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None, text, ["missing YAML front matter"]
    problems: list[str] = []
    try:
        loaded = yaml.safe_load(m.group(1))
    except yaml.YAMLError as e:
        problems.append(f"invalid front matter: {str(e).splitlines()[0]}")
        loaded = {}
    if not isinstance(loaded, dict):
        problems.append("front matter must be a mapping")
        loaded = {}
    return loaded, text[m.end() :], problems


def parse_node(node_id: str, rel: str, text: str) -> tuple[Node, list[str]]:
    meta, body, problems = parse_front_matter(text)
    if meta is not None:
        problems += validate_meta(meta)
    sections, section_problems = split_sections(body)
    problems += section_problems
    node = Node(node_id, rel, meta or {}, sections)
    for name in ("Summary", "Design"):
        if name in sections and not sections[name]:
            problems.append(f"{name} is empty")
    if "Behavior" in sections:
        node.behavior, found = parse_behavior(sections["Behavior"])
        problems += found
    if "History" in sections:
        node.history, found = parse_history(sections["History"])
        problems += found
    if "Known gaps" in sections:
        problems += check_gaps(sections["Known gaps"])
    return node, problems


def validate_meta(meta: dict) -> list[str]:
    problems = [f"missing field '{k}'" for k in REQUIRED if k not in meta]
    for key in meta:
        if key == "id":
            problems.append("id is derived from the path; remove the id field")
        elif key not in REQUIRED + OPTIONAL:
            problems.append(f"unknown field '{key}'")
    title = meta.get("title")
    if "title" in meta and not (isinstance(title, str) and title.strip()):
        problems.append("title must be a non-empty string")
    status = meta.get("status")
    if "status" in meta and status not in STATUSES:
        problems.append(f"status must be one of {', '.join(STATUSES)}")
    if "review" in meta and meta["review"] not in REVIEWS:
        problems.append(f"review must be one of {', '.join(REVIEWS)}")
    sha = meta.get("reviewed_at")
    if "reviewed_at" in meta and not (isinstance(sha, str) and SHA_RE.fullmatch(sha)):
        problems.append("reviewed_at must be a full 40-character SHA, quoted if YAML reads it as a number")
    if "origin" in meta:
        problems += validate_origin(meta["origin"])
    branch = meta.get("branch")
    if status == "in-progress" and not (isinstance(branch, str) and branch.strip()):
        problems.append("branch is required while status is in-progress")
    if status != "in-progress" and branch is not None:
        problems.append("branch must be null unless status is in-progress")
    for key in LIST_FIELDS:
        value = meta.get(key, [])
        if not (isinstance(value, list) and all(isinstance(v, str) and v for v in value)):
            problems.append(f"{key} must be a list of non-empty strings")
    return problems


def validate_origin(origin: object) -> list[str]:
    if not isinstance(origin, dict) or set(origin) != {"issue", "pr"}:
        return ["origin must be {issue: <ref>|null, pr: <ref>|null}"]
    problems = []
    for key, value in origin.items():
        if value is not None and not (isinstance(value, str) and re.fullmatch(REF, value)):
            problems.append(f"origin.{key} must be owner/repo#n or null")
    if origin["issue"] is None and origin["pr"] is None:
        problems.append("origin needs an issue or a PR")
    return problems


def split_sections(body: str, expected: tuple[str, ...] = SECTIONS) -> tuple[dict[str, str], list[str]]:
    sections: dict[str, str] = {}
    order: list[str] = []
    problems: list[str] = []
    current: str | None = None
    lines: list[str] = []
    preamble: list[str] = []
    fenced = False
    for line in body.splitlines():
        if line.startswith("```"):
            fenced = not fenced
        if not fenced and line.startswith("# "):
            problems.append("no '#' title; the title lives in front matter")
            continue
        if not fenced and line.startswith("## "):
            if current is not None:
                sections[current] = "\n".join(lines).strip()
            current = line[3:].strip()
            order.append(current)
            lines = []
            continue
        (lines if current is not None else preamble).append(line)
    if current is not None:
        sections[current] = "\n".join(lines).strip()
    if any(line.strip() for line in preamble):
        problems.append("content before the first section")
    if order != list(expected):
        missing = [s for s in expected if s not in order]
        extra = [s for s in order if s not in expected]
        if missing:
            problems.append(f"missing section(s): {', '.join(missing)}")
        if extra:
            problems.append(f"unexpected section(s): {', '.join(extra)}")
        if not missing and not extra:
            problems.append(f"sections must appear once each, in order: {', '.join(expected)}")
    return sections, problems


def parse_bullets(text: str, section: str, subheadings: bool) -> tuple[list[str], list[str]]:
    bullets: list[str] = []
    problems: list[str] = []
    for line in text.splitlines():
        if not line.strip() or (subheadings and line.startswith("### ")):
            continue
        if line.startswith("- "):
            bullets.append(line[2:].strip())
        elif bullets and line.startswith("  ") and not line.lstrip().startswith(("- ", "* ")):
            bullets[-1] += " " + line.strip()
        else:
            allowed = "'- ' bullets and '###' subheadings" if subheadings else "'- ' bullets"
            problems.append(f"{section} allows only {allowed}: {line.strip()[:60]!r}")
    return bullets, problems


def parse_behavior(text: str) -> tuple[list[str], list[str]]:
    bullets, problems = parse_bullets(text, "Behavior", subheadings=True)
    for bullet in bullets:
        if not CITED_RE.search(" " + bullet):
            problems.append(f"Behavior bullet lacks a trailing citation: {bullet[:60]!r}")
    return bullets, problems


def parse_history(text: str) -> tuple[list[dict], list[str]]:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    if not lines or not all(line.startswith("|") and line.endswith("|") for line in lines):
        return [], ["History must be a single table"]
    cells = [[c.strip() for c in re.split(r"(?<!\\)\|", line[1:-1])] for line in lines]
    problems = []
    if cells[0] != HISTORY_HEADER:
        problems.append("History header must be | Date | PR | Type | Change |")
    if len(cells) < 2 or not all(re.fullmatch(r":?-+:?", c) for c in cells[1]):
        problems.append("History table is missing its separator row")
    rows = []
    for number, row in enumerate(cells[2:], 1):
        if len(row) != 4:
            problems.append(f"History row {number} needs 4 cells")
            continue
        date, pr, kind, change = row
        if not DATE_RE.fullmatch(date):
            problems.append(f"History row {number}: Date must be YYYY-MM-DD")
        if not re.fullmatch(REF, pr):
            problems.append(f"History row {number}: PR must be owner/repo#n")
        if kind.rstrip("!") not in TYPES:
            problems.append(f"History row {number}: Type must be one of {', '.join(TYPES)}")
        if not change:
            problems.append(f"History row {number}: Change is empty")
        rows.append({"date": date, "pr": pr, "type": kind, "change": change})
    dates = [r["date"] for r in rows]
    if dates != sorted(dates, reverse=True):
        problems.append("History must be newest first")
    seen = [r["pr"] for r in rows]
    for pr in sorted({p for p in seen if seen.count(p) > 1}):
        problems.append(f"History lists {pr} more than once")
    return rows, problems


def check_gaps(text: str) -> list[str]:
    if text == "None known.":
        return []
    bullets, problems = parse_bullets(text, "Known gaps", subheadings=False)
    if not bullets and not problems:
        return ["Known gaps is empty; write 'None known.'"]
    for bullet in bullets:
        if not re.search(REF, bullet):
            problems.append(f"Known gaps bullet must cite an issue: {bullet[:60]!r}")
    return problems


# Sweeps


def load_sweeps(root: Path) -> Sweeps:
    folder = root / "qa" / "sweeps"
    sweeps = Sweeps({}, [])
    if not folder.is_dir():
        sweeps.issues.append(Issue("error", "qa/sweeps/", "directory is missing"))
        return sweeps
    for path in sorted(folder.iterdir()):
        if path.name.startswith("."):
            continue
        rel = path.relative_to(root).as_posix()
        if path.is_dir() or path.suffix != ".md":
            sweeps.issues.append(Issue("error", rel, "only Markdown files belong under qa/sweeps/"))
            continue
        sweep, problems = parse_sweep(path.stem, rel, path.read_text())
        sweeps.sweeps[path.stem] = sweep
        sweeps.issues.extend(Issue("error", rel, p) for p in problems)
    return sweeps


def parse_sweep(area: str, rel: str, text: str) -> tuple[Sweep, list[str]]:
    meta, body, problems = parse_front_matter(text)
    if meta is not None:
        problems += validate_sweep_meta(meta)
    sections, found = split_sections(body, SWEEP_SECTIONS)
    problems += found
    sweep = Sweep(area, rel, meta or {}, sections)
    for name in ("Scope", "Setup"):
        if name in sections and not sections[name]:
            problems.append(f"{name} is empty")
    if "Probes" in sections:
        sweep.probes, found = parse_probes(sections["Probes"])
        problems += found
    if "Hand-offs" in sections:
        sweep.handoffs, found = parse_handoffs(sections["Hand-offs"])
        problems += found
    return sweep, problems


def validate_sweep_meta(meta: dict) -> list[str]:
    problems = [f"missing field '{k}'" for k in SWEEP_REQUIRED if k not in meta]
    problems += [f"unknown field '{k}'" for k in meta if k not in SWEEP_REQUIRED + SWEEP_OPTIONAL]
    title = meta.get("title")
    if "title" in meta and not (isinstance(title, str) and title.strip()):
        problems.append("title must be a non-empty string")
    sha = meta.get("reviewed_at")
    if "reviewed_at" in meta and not (isinstance(sha, str) and SHA_RE.fullmatch(sha)):
        problems.append("reviewed_at must be a full 40-character SHA, quoted if YAML reads it as a number")
    for key in SWEEP_OPTIONAL:
        value = meta.get(key, [])
        if not (isinstance(value, list) and all(isinstance(v, str) and v for v in value)):
            problems.append(f"{key} must be a list of non-empty strings")
    return problems


def parse_probes(text: str) -> tuple[dict[str | None, list[str]], list[str]]:
    """Bullets grouped by `### <node id>`; bullets before the first heading are keyed None."""
    probes: dict[str | None, list[str]] = {}
    problems: list[str] = []
    current: str | None = None
    for line in text.splitlines():
        if not line.strip():
            continue
        if line.startswith("### "):
            current = line[4:].strip().strip("`")
            probes.setdefault(current, [])
        elif line.startswith("- "):
            probes.setdefault(current, []).append(line[2:].strip())
        elif probes.get(current) and line.startswith("  ") and not line.lstrip().startswith(("- ", "* ")):
            probes[current][-1] += " " + line.strip()
        else:
            problems.append(f"Probes allows only '- ' bullets and '###' subheadings: {line.strip()[:60]!r}")
    return probes, problems


def parse_handoffs(text: str) -> tuple[list[tuple[str, str]], list[str]]:
    if text == "None.":
        return [], []
    bullets, problems = parse_bullets(text, "Hand-offs", subheadings=False)
    if not bullets and not problems:
        return [], ["Hand-offs is empty; write 'None.'"]
    handoffs = []
    for bullet in bullets:
        m = HANDOFF_RE.match(bullet)
        if m:
            handoffs.append((m.group(1), m.group(2)))
        else:
            problems.append(f"Hand-off must read '<what> → `<sweep>`': {bullet[:60]!r}")
    return handoffs, problems


# Checking


def normalize(bullet: str) -> str:
    text = re.sub(rf"(?:,?\s*{REF})+(?:\s\(unverified\))?$", "", bullet)
    return " ".join(text.lower().split())


def check(root: Path, lister=None) -> list[Issue]:
    """`lister(sha)` returns upstream paths at that commit, or None if unknown. None skips the path check."""
    tree = load_tree(root)
    issues = list(tree.issues)
    sources = load_sources(root)
    scopes = load_scopes(root)
    if not isinstance(sources.get("upstream"), dict) or not sources["upstream"].get("repo"):
        issues.append(Issue("error", "sources.yaml", "upstream.repo is required"))
    watermark = sources.get("watermark")
    if watermark is not None and not (isinstance(watermark, str) and SHA_RE.fullmatch(watermark)):
        issues.append(Issue("error", "sources.yaml", "watermark must be null or a full 40-character SHA"))
    for scope, target in sorted(scopes.mapping.items()):
        if target is not None and target not in tree.nodes:
            issues.append(Issue("error", "scopes.yaml", f"scope '{scope}' maps to missing node '{target}'"))
        if scope in scopes.ignore:
            issues.append(Issue("error", "scopes.yaml", f"scope '{scope}' is both mapped and ignored"))
    for node_id in sorted(scopes.fallback):
        if node_id not in tree.nodes:
            issues.append(Issue("error", "scopes.yaml", f"fallback names missing node '{node_id}'"))
    for node_id in tree.ordered():
        node = tree.nodes[node_id]
        issues += [Issue("error", node.path, m) for m in tree_problems(tree, node)]
        if lister is not None:
            issues += [Issue("error", node.path, m) for m in path_problems(node, lister)]
    sweeps = load_sweeps(root)
    issues += sweeps.issues
    for area in sorted(sweeps.sweeps):
        sweep = sweeps.sweeps[area]
        issues += [Issue("error", sweep.path, m) for m in sweep_problems(tree, sweeps, sweep)]
        if lister is not None:
            issues += sweep_path_issues(tree, sweep, lister)
    issues += area_issues(tree, sweeps)
    if not any(i.level == "error" and i.where.startswith(("features", "qa/")) for i in issues):
        rendered = render_index(tree, sources, load_dataset(root), sweeps)
        stale = [p for p, text in rendered.items() if read(root / p) != text]
        if stale:
            issues.append(Issue("error", ", ".join(stale), "stale index; run featuremap.py index"))
    return issues


def tree_problems(tree: Tree, node: Node) -> list[str]:
    problems = []
    for related in node.listed("related"):
        if related == node.id:
            problems.append("related lists the node itself")
        elif related not in tree.nodes:
            problems.append(f"related id '{related}' does not exist")
    ancestors = tree.ancestors(node.id)
    own = {normalize(b) for b in node.behavior}
    for ancestor in ancestors:
        for bullet in tree.nodes[ancestor].behavior:
            if normalize(bullet) in own:
                problems.append(f"Behavior bullet also in ancestor {ancestor}: {bullet[:60]!r}")
        prs = {r["pr"] for r in tree.nodes[ancestor].history}
        for row in node.history:
            if row["pr"] in prs:
                problems.append(f"{row['pr']} also has a History row on ancestor {ancestor}")
    if node.meta.get("status") == "shipped" and not node.behavior and not tree.children(node.id):
        problems.append("a shipped leaf needs Behavior bullets")
    return problems


def path_problems(node: Node, lister) -> list[str]:
    sha = node.reviewed_at()
    if sha is None:
        return []
    files = lister(sha)
    if files is None:
        return [f"reviewed_at {sha[:7]} is not an upstream commit"]
    return [
        f"{key} entry {pattern!r} matches nothing upstream at {sha[:7]}"
        for key in ("code", "tests", "docs")
        for pattern in node.listed(key)
        if not any(matches(pattern, f) for f in files)
    ]


def sweep_problems(tree: Tree, sweeps: Sweeps, sweep: Sweep) -> list[str]:
    problems = []
    for heading, bullets in sweep.probes.items():
        if heading is None:
            continue
        if heading not in tree.nodes or heading.split("/")[0] != sweep.area:
            problems.append(f"Probes subheading '{heading}' is not a node under features/{sweep.area}/")
        elif not bullets:
            problems.append(f"Probes subheading '{heading}' has no bullets")
    for _, target in sweep.handoffs:
        if target == sweep.area:
            problems.append("hand-off lists the sweep itself")
        elif target not in sweeps.sweeps:
            problems.append(f"hand-off target '{target}' is not a sweep")
    return problems


def area_issues(tree: Tree, sweeps: Sweeps) -> list[Issue]:
    areas = {n.split("/")[0] for n in tree.nodes}
    issues = [
        Issue("error", "qa/sweeps/", f"area '{area}' has no sweep; add qa/sweeps/{area}.md")
        for area in sorted(areas - set(sweeps.sweeps))
    ]
    issues += [
        Issue("error", sweeps.sweeps[name].path, f"'{name}' is not an area under features/")
        for name in sorted(set(sweeps.sweeps) - areas)
    ]
    return issues


def sweep_path_issues(tree: Tree, sweep: Sweep, lister) -> list[Issue]:
    sha = sweep.reviewed_at()
    if sha is None:
        return []
    files = lister(sha)
    if files is None:
        return [Issue("error", sweep.path, f"reviewed_at {sha[:7]} is not an upstream commit")]
    issues = [
        Issue("error", sweep.path, f"{key} entry {pattern!r} matches nothing upstream at {sha[:7]}")
        for key in SWEEP_OPTIONAL
        for pattern in sweep.listed(key)
        if not any(matches(pattern, f) for f in files)
    ]
    for trigger in sweep.listed("triggers"):
        hit = [f for f in files if matches(trigger, f)]
        owners = sorted(n for n, node in tree.nodes.items() if any(matches(p, f) for f in hit for p in node.listed("code")))
        if owners:
            issues.append(Issue("warning", sweep.path, f"trigger {trigger!r} is already owned by {', '.join(owners)}"))
    return issues


def read(path: Path) -> str | None:
    return path.read_text() if path.exists() else None


# Mapping


def touched(tree: Tree, files: list[str]) -> dict[str, int]:
    hits = {}
    for node_id, node in tree.nodes.items():
        count = sum(1 for f in files if any(matches(p, f) for p in node.patterns()))
        if count:
            hits[node_id] = count
    return hits


def common_prefix(ids: list[str]) -> str:
    common = []
    for segments in zip(*(i.split("/") for i in ids)):
        if len(set(segments)) != 1:
            break
        common.append(segments[0])
    return "/".join(common)


def yield_fallback(tree: Tree, scopes: Scopes, pool: list[str], files: list[str]) -> list[str]:
    """Drop fallback nodes when other nodes in the pool own at least as many of the files."""
    others = [n for n in pool if n not in scopes.fallback]
    if not others or len(others) == len(pool):
        return pool

    def owned(ids: list[str]) -> int:
        return sum(1 for f in files if any(matches(p, f) for n in ids for p in tree.nodes[n].patterns()))

    return others if owned(others) >= owned([n for n in pool if n in scopes.fallback]) else pool


def assign(tree: Tree, scopes: Scopes, pr: dict) -> Assignment:
    """Scope picks the subtree, touched paths pick the most specific node in it."""
    hits = touched(tree, pr.get("files") or [])
    affected = sorted(hits, key=id_key)
    scope = pr.get("scope")
    if scope in scopes.ignore:
        return Assignment(None, f"ignored scope '{scope}'", affected)
    target = scopes.mapping.get(scope) if scope else None
    if target and target not in tree.nodes:
        return Assignment(None, f"scope '{scope}' maps to missing node '{target}'", affected)
    pool = [n for n in affected if not target or n == target or n.startswith(target + "/")]
    pool = yield_fallback(tree, scopes, pool, pr.get("files") or [])
    leaves = [n for n in pool if not any(o.startswith(n + "/") for o in pool)]
    if len(leaves) == 1:
        return Assignment(leaves[0], "scope and paths" if target else "paths", affected)
    if leaves:
        shared = common_prefix(leaves)
        if shared in tree.nodes:
            return Assignment(shared, "paths span its children", affected)
        if target:
            return Assignment(target, f"scope '{scope}'; paths span several children", affected)
        return Assignment(None, "touches several features: " + ", ".join(leaves), affected)
    if target:
        return Assignment(target, f"scope '{scope}'", affected)
    return Assignment(None, f"scope '{scope}' is unmapped" if scope else "no scope and no matching paths", affected)


def radius(tree: Tree, sweeps: Sweeps, primary: list[str], files: list[str], owner: str | None = None) -> Radius:
    """Primary nodes plus the nodes a change to them can regress, each in the lowest tier that reaches it."""
    primary = sorted({p for p in primary if p in tree.nodes}, key=id_key)
    seen = set(primary)
    tiers: dict[int, list[str]] = {1: [], 2: [], 3: []}
    why: dict[str, str] = {}

    def add(tier: int, candidates: list[tuple[str, str]]) -> None:
        for node_id, reason in sorted(candidates, key=lambda c: id_key(c[0])):
            if node_id in tree.nodes and node_id not in seen:
                seen.add(node_id)
                tiers[tier].append(node_id)
                why[node_id] = reason

    add(1, [(a, f"ancestor of `{p}`") for p in primary for a in tree.ancestors(p)]
        + [(s, f"under `{p}`") for p in primary for s in tree.subtree(p)])
    add(2, [(r, f"related from `{p}`") for p in primary for r in tree.nodes[p].listed("related")])
    add(3, [(n, f"lists `{p}` as related") for n, node in tree.nodes.items() for p in primary
            if p in node.listed("related")])
    forced: dict[str, list[str]] = {}
    for area, sweep in sorted(sweeps.sweeps.items()):
        reasons = []
        for trigger in sweep.listed("triggers"):
            hit = [f for f in files if matches(trigger, f)]
            if len(hit) == 1:
                reasons.append(f"trigger `{trigger}` matched `{hit[0]}`")
            elif hit:
                reasons.append(f"trigger `{trigger}` matched {len(hit)} files, e.g. `{hit[0]}`")
        if reasons:
            forced[area] = reasons
    patterns = [p for n in tree.nodes.values() for p in n.patterns() + n.listed("docs")]
    patterns += [t for s in sweeps.sweeps.values() for t in s.listed("triggers")]
    unmapped = [f for f in files if not any(matches(p, f) for p in patterns)]
    return Radius(primary, touched(tree, files), owner, tiers, why, forced, unmapped)


def launch(radius: Radius, sweeps: Sweeps, upto: int) -> dict[str, list[str]]:
    """Sweep name -> why it runs: it owns a primary or tiered node, or a trigger fired."""
    reasons: dict[str, list[str]] = {}
    for node_id in radius.nodes(upto):
        area = sweeps.owner(node_id)
        if area is None:
            continue
        tier = radius.tier_of(node_id)
        reasons.setdefault(area, []).append(
            f"owns primary `{node_id}`" if tier == 0 else f"owns tier-{tier} node `{node_id}`"
        )
    for area, why in radius.forced.items():
        reasons.setdefault(area, []).extend(why)
    return dict(sorted(reasons.items()))


def rust_filter(path: str) -> str | None:
    """`src/a/b/tests/c.rs` -> `a::b::tests::c`, the libtest filter for that module; None when not a module path."""
    if any(c in path for c in "*?") or not path.startswith("src/") or not path.endswith(".rs"):
        return None
    parts = path[len("src/") : -len(".rs")].split("/")
    if parts[-1] in ("mod", "lib", "main"):
        parts = parts[:-1]
    return "::".join(parts) or None


# Indexes


def render_index(tree: Tree, sources: dict, dataset: dict[int, dict], sweeps: Sweeps | None = None) -> dict[str, str]:
    upstream = sources.get("upstream") if isinstance(sources.get("upstream"), dict) else {}
    repo = upstream.get("repo", "lgse/strata")
    sweeps = sweeps or Sweeps({}, [])
    since = {n: changes_since(tree, n, dataset) for n in tree.ordered()}
    return {
        "README.md": render_readme(tree, repo, sources.get("watermark"), since, sweeps),
        "index/by-area.md": render_by_area(tree, repo, since),
        "index/by-path.md": render_by_path(tree),
        "index/by-pr.md": render_by_pr(tree),
        "index/qa.md": render_qa(tree, sweeps, repo),
    }


def inherited_docs(tree: Tree, node_id: str) -> list[str]:
    return [d for a in tree.ancestors(node_id) for d in tree.nodes[a].listed("docs")]


def e2e_entries(tree: Tree, node_id: str, subtree: bool = False) -> list[str]:
    ids = tree.subtree(node_id) if subtree else [node_id]
    return sorted({t for n in ids for t in tree.nodes[n].listed("tests") if t.startswith(E2E_PREFIX)})


def changes_since(tree: Tree, node_id: str, dataset: dict[int, dict]) -> str:
    """PRs touching the subtree merged after its oldest review; '?' when a review commit is not in the dataset."""
    merged = {row.get("merge_commit"): row.get("merged_at") for row in dataset.values()}
    subtree = [tree.nodes[n] for n in tree.subtree(node_id)]
    dates = [merged.get(n.reviewed_at()) for n in subtree]
    if not dataset or any(d is None for d in dates):
        return "?"
    oldest = min(dates)
    patterns = [p for n in subtree for p in n.patterns()]
    count = sum(
        1
        for row in dataset.values()
        if (row.get("merged_at") or "") > oldest
        and any(matches(p, f) for f in row.get("files") or [] for p in patterns)
    )
    return str(count)


def ref_link(ref: str) -> str:
    repo, number = ref.split("#")
    return f"[{ref}](https://github.com/{repo}/issues/{number})"


def path_link(repo: str, sha: str | None, pattern: str) -> str:
    rev = sha or "HEAD"
    if not any(c in pattern for c in "*?"):
        return f"[`{pattern}`](https://github.com/{repo}/blob/{rev}/{pattern})"
    static = []
    for segment in pattern.split("/"):
        if any(c in segment for c in "*?"):
            break
        static.append(segment)
    return f"[`{pattern}`](https://github.com/{repo}/tree/{rev}/{'/'.join(static)})"


def node_link(tree: Tree, node_id: str, prefix: str = "") -> str:
    node = tree.nodes[node_id]
    return f"[{node.meta.get('title') or node_id}]({prefix}{node.path})"


def render_readme(tree: Tree, repo: str, watermark: object, since: dict[str, str], sweeps: Sweeps) -> str:
    reviewed = sum(1 for n in tree.nodes.values() if n.meta.get("review") == "reviewed")
    mark = f"`{watermark[:7]}`" if isinstance(watermark, str) else "not set"
    out = [
        GENERATED,
        "",
        "# Strata feature map",
        "",
        "One Markdown file per Strata feature, tying shipped behavior and design to the upstream issues and "
        "PRs that produced it. [AGENTS.md](AGENTS.md) holds the schema and the rules for editing it.",
        "",
        "Look features up [by area](index/by-area.md), [by path](index/by-path.md), [by PR](index/by-pr.md), "
        "or [by QA sweep](index/qa.md). "
        "*PRs since* counts upstream PRs touching a feature or its children since the oldest review in its "
        "subtree; `?` means the review commit is not in `data/prs.jsonl` yet. "
        "[qa/README.md](qa/README.md) says how to QA a PR or sweep an area.",
        "",
        f"Upstream [{repo}](https://github.com/{repo}) · watermark {mark} · "
        f"{len(tree.nodes)} features, {reviewed} reviewed",
    ]
    areas = sorted({n.split("/")[0] for n in tree.nodes})
    if not areas:
        out += ["", "No features yet."]
    for area in areas:
        out += ["", f"## {area}", ""]
        if area in sweeps.sweeps:
            out += [f"QA sweep: [`{sweeps.sweeps[area].path}`]({sweeps.sweeps[area].path})", ""]
        out += ["| Feature | Id | Status | Review | Reviewed at | PRs since |"]
        out.append("| --- | --- | --- | --- | --- | --- |")
        for node_id in [n for n in tree.ordered() if n.split("/")[0] == area]:
            node = tree.nodes[node_id]
            indent = "&emsp;" * (node.depth - 3) + "↳ " if node.depth > 2 else ""
            sha = node.reviewed_at()
            out.append(
                f"| {indent}{node_link(tree, node_id)} | `{node_id}` | {node.meta.get('status')} | "
                f"{node.meta.get('review')} | {f'`{sha[:7]}`' if sha else '—'} | {since[node_id]} |"
            )
    return "\n".join(out) + "\n"


def render_by_area(tree: Tree, repo: str, since: dict[str, str]) -> str:
    out = [GENERATED, "", "# Features by area"]
    area = None
    for node_id in tree.ordered():
        node = tree.nodes[node_id]
        if node_id.split("/")[0] != area:
            area = node_id.split("/")[0]
            out += ["", f"## {area}"]
        sha = node.reviewed_at()
        reviewed = f"reviewed at [`{sha[:7]}`](https://github.com/{repo}/tree/{sha})" if sha else "not reviewed"
        out += [
            "",
            f"### {node_link(tree, node_id, '../')} `{node_id}`",
            "",
            f"{node.meta.get('status')} · {node.meta.get('review')} · {reviewed} · {since[node_id]} PRs since",
        ]
        origin = node.meta.get("origin") if isinstance(node.meta.get("origin"), dict) else {}
        refs = [f"{k} {ref_link(v)}" for k, v in origin.items() if isinstance(v, str) and re.fullmatch(REF, v)]
        if refs:
            out[-1] += " · origin " + ", ".join(refs)
        if node.sections.get("Summary"):
            out += ["", node.sections["Summary"]]
        inherited = inherited_docs(tree, node_id)
        rows = [
            ("Code", [path_link(repo, sha, p) for p in node.listed("code")]),
            ("Tests", [path_link(repo, sha, p) for p in node.listed("tests")]),
            ("Docs", [path_link(repo, sha, p) for p in node.listed("docs")]
             + [path_link(repo, sha, p) + " (inherited)" for p in inherited]),
            ("Related", [node_link(tree, r, "../") for r in node.listed("related") if r in tree.nodes]),
            ("Children", [node_link(tree, c, "../") for c in tree.children(node_id)]),
        ]
        items = [f"- {label}: {', '.join(values)}" for label, values in rows if values]
        if items:
            out += [""] + items
    if not tree.nodes:
        out += ["", "No features yet."]
    return "\n".join(out) + "\n"


def render_by_path(tree: Tree) -> str:
    out = [
        GENERATED,
        "",
        "# Features by path",
        "",
        "Each upstream path or glob with the node that owns it and that node's ancestors, which share its coverage.",
        "",
        "| Path | Kind | Node | Ancestors |",
        "| --- | --- | --- | --- |",
    ]
    rows = sorted(
        (pattern, kind, node_id)
        for node_id, node in tree.nodes.items()
        for kind in ("code", "tests")
        for pattern in node.listed(kind)
    )
    for pattern, kind, node_id in rows:
        ancestors = ", ".join(node_link(tree, a, "../") for a in reversed(tree.ancestors(node_id))) or "—"
        out.append(f"| `{pattern}` | {kind} | {node_link(tree, node_id, '../')} | {ancestors} |")
    return "\n".join(out) + "\n"


def render_by_pr(tree: Tree) -> str:
    out = [
        GENERATED,
        "",
        "# Features by PR",
        "",
        "Every History row across the tree, newest first.",
        "",
        "| PR | Date | Type | Node | Change |",
        "| --- | --- | --- | --- | --- |",
    ]
    rows = [(r, node_id) for node_id, node in tree.nodes.items() for r in node.history]
    rows.sort(key=lambda item: (item[0]["date"], int(item[0]["pr"].split("#")[1]), item[1]), reverse=True)
    for row, node_id in rows:
        out.append(
            f"| {ref_link(row['pr'])} | {row['date']} | {row['type']} | {node_link(tree, node_id, '../')} | "
            f"{row['change']} |"
        )
    return "\n".join(out) + "\n"


def render_qa(tree: Tree, sweeps: Sweeps, repo: str) -> str:
    out = [
        GENERATED,
        "",
        "# QA sweeps",
        "",
        "One sweep per area owns every node under it. [qa/README.md](../qa/README.md) says how to run a sweep; "
        "`scripts/featuremap.py qa` builds the plan for a PR, a diff, a node, or a sweep.",
    ]
    areas = sorted({n.split("/")[0] for n in tree.nodes} | set(sweeps.sweeps))
    for area in areas:
        sweep = sweeps.sweeps.get(area)
        nodes = [n for n in tree.ordered() if n.split("/")[0] == area]
        if sweep is None:
            out += ["", f"## `{area}`", "", f"No sweep. Add `qa/sweeps/{area}.md`."]
            continue
        sha = sweep.reviewed_at()
        reviewed = f"reviewed at [`{sha[:7]}`](https://github.com/{repo}/tree/{sha})" if sha else "not reviewed"
        probed = sum(1 for n in nodes if sweep.probes.get(n))
        out += ["", f"## [{sweep.meta.get('title') or area}](../{sweep.path}) `{area}`", ""]
        out.append(f"{reviewed} · {len(nodes)} nodes, {probed} with probes")
        lines = []
        if sweep.listed("triggers"):
            lines.append("- Triggers: " + ", ".join(path_link(repo, sha, t) for t in sweep.listed("triggers")))
        if sweep.listed("tools"):
            lines.append("- Tools: " + ", ".join(path_link(repo, sha, t) for t in sweep.listed("tools")))
        if sweep.handoffs:
            lines.append("- Hand-offs: " + "; ".join(f"{what} → [`{t}`](../qa/sweeps/{t}.md)" for what, t in sweep.handoffs))
        if lines:
            out += [""] + lines
        out += ["", "| Node | Probes | E2E scenarios | Other tests | Docs |", "| --- | --- | --- | --- | --- |"]
        for node_id in nodes:
            node = tree.nodes[node_id]
            node_sha = node.reviewed_at()
            indent = "&emsp;" * (node.depth - 3) + "↳ " if node.depth > 2 else ""
            e2e = [path_link(repo, node_sha, t) for t in node.listed("tests") if t.startswith(E2E_PREFIX)]
            other = len(node.listed("tests")) - len(e2e)
            docs = [path_link(repo, node_sha, d) for d in node.listed("docs")]
            docs += [path_link(repo, node_sha, d) + " (inherited)" for d in inherited_docs(tree, node_id)]
            out.append(
                f"| {indent}{node_link(tree, node_id, '../')} `{node_id}` | {len(sweep.probes.get(node_id, []))} | "
                f"{', '.join(e2e) or '—'} | {other} | {', '.join(docs) or '—'} |"
            )
    unprobed = [n for n in tree.ordered() if not (sweeps.sweeps.get(n.split("/")[0]) or Sweep("", "", {}, {})).probes.get(n)]
    out += ["", f"## Nodes without probes ({len(unprobed)})", "",
            "Their Behavior bullets are the whole checklist."]
    out += [""] + [f"- {node_link(tree, n, '../')} `{n}`" for n in unprobed] if unprobed else ["", "None."]
    no_e2e = [n for n in tree.ordered() if not e2e_entries(tree, n, subtree=True)]
    out += ["", f"## Nodes without E2E scenarios ({len(no_e2e)})", "",
            "Neither the node nor its subtree cites a `tests/e2e/` scenario, so QA here is manual or Rust-level."]
    out += [""] + [f"- {node_link(tree, n, '../')} `{n}`" for n in no_e2e] if no_e2e else ["", "None."]
    return "\n".join(out) + "\n"


def write_index(root: Path) -> list[str]:
    tree = load_tree(root)
    written = []
    for rel, text in render_index(tree, load_sources(root), load_dataset(root), load_sweeps(root)).items():
        path = root / rel
        if read(path) != text:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            written.append(rel)
    return written


# Upstream access


class Upstream:
    """A blobless bare clone of upstream in .cache/, or a read-only clone named by FEATUREMAP_UPSTREAM."""

    def __init__(self, root: Path, sources: dict):
        upstream = sources.get("upstream") or {}
        self.repo = upstream.get("repo", "lgse/strata")
        self.branch = upstream.get("branch", "main")
        configured = os.environ.get("FEATUREMAP_UPSTREAM")
        self.managed = configured is None
        self.git_dir = Path(configured) if configured else root / ".cache" / "upstream.git"
        self.ref = os.environ.get("FEATUREMAP_UPSTREAM_REF") or f"refs/heads/{self.branch}"
        self.synced = False
        self.trees: dict[str, set[str] | None] = {}

    def git(self, *args: str) -> str:
        result = subprocess.run(["git", "-C", str(self.git_dir), *args], capture_output=True, text=True)
        if result.returncode:
            raise SystemExit(f"git {' '.join(args)} failed: {result.stderr.strip()}")
        return result.stdout

    def sync(self) -> None:
        if not self.managed or self.synced:
            return
        self.synced = True
        if not self.git_dir.exists():
            self.git_dir.parent.mkdir(parents=True, exist_ok=True)
            url = f"https://github.com/{self.repo}.git"
            subprocess.run(["git", "clone", "--quiet", "--bare", "--filter=blob:none", url, str(self.git_dir)], check=True)
        else:
            self.git("fetch", "--quiet", "--filter=blob:none", "origin", f"+refs/heads/{self.branch}:refs/heads/{self.branch}")

    def has(self, sha: str) -> bool:
        if not self.git_dir.exists():
            return False
        probe = ["git", "-C", str(self.git_dir), "cat-file", "-e", f"{sha}^{{commit}}"]
        return subprocess.run(probe, capture_output=True).returncode == 0

    def files(self, sha: str) -> set[str] | None:
        if sha not in self.trees:
            if not self.has(sha):
                self.sync()
            self.trees[sha] = set(self.git("ls-tree", "-r", "--name-only", sha).splitlines()) if self.has(sha) else None
        return self.trees[sha]

    def head(self) -> str:
        self.sync()
        return self.git("rev-parse", self.ref).strip()

    def log(self, base: str, head: str) -> list[tuple[str, str]]:
        out = self.git("log", "--first-parent", "--format=%H%x09%s", f"{base}..{head}")
        return [tuple(line.split("\t", 1)) for line in out.splitlines()]

    def commits(self, base: str, head: str) -> set[str]:
        return set(self.git("rev-list", "--first-parent", f"{base}..{head}").split())


# GitHub access

LIST_QUERY = """
query($owner: String!, $name: String!, $base: String!, $cursor: String) {
  repository(owner: $owner, name: $name) {
    pullRequests(states: MERGED, baseRefName: $base, first: 100, after: $cursor,
                 orderBy: {field: CREATED_AT, direction: ASC}) {
      pageInfo { hasNextPage endCursor }
      nodes { number }
    }
  }
}"""

PR_FIELDS = """
  number title body mergedAt headRefOid
  mergeCommit { oid }
  author { login }
  labels(first: 20) { nodes { name } }
  files(first: 100) { pageInfo { hasNextPage endCursor } nodes { path } }
  closingIssuesReferences(first: 10) {
    nodes {
      number title state body repository { nameWithOwner }
      comments(first: 100) { nodes { author { login } createdAt body } }
    }
  }"""

FILES_QUERY = """
query($owner: String!, $name: String!, $number: Int!, $cursor: String) {
  repository(owner: $owner, name: $name) {
    pullRequest(number: $number) {
      files(first: 100, after: $cursor) { pageInfo { hasNextPage endCursor } nodes { path } }
    }
  }
}"""


def graphql(query: str, **variables: object) -> dict:
    args = ["gh", "api", "graphql", "-f", f"query={query}"]
    for key, value in variables.items():
        args += ["-F" if isinstance(value, int) else "-f", f"{key}={value}"]
    result = subprocess.run(args, capture_output=True, text=True)
    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError:
        raise SystemExit(f"gh api graphql failed: {result.stderr.strip()}")
    if result.returncode or data.get("errors"):
        raise SystemExit(f"gh api graphql failed: {data.get('errors') or result.stderr.strip()}")
    return data["data"]


def merged_pr_numbers(repo: str, branch: str) -> list[int]:
    owner, name = repo.split("/")
    numbers: list[int] = []
    cursor = None
    while True:
        variables = {"owner": owner, "name": name, "base": branch} | ({"cursor": cursor} if cursor else {})
        page = graphql(LIST_QUERY, **variables)["repository"]["pullRequests"]
        numbers += [n["number"] for n in page["nodes"]]
        if not page["pageInfo"]["hasNextPage"]:
            return numbers
        cursor = page["pageInfo"]["endCursor"]


def fetch_prs(repo: str, numbers: list[int], batch: int = 10):
    owner, name = repo.split("/")
    for start in range(0, len(numbers), batch):
        chunk = numbers[start : start + batch]
        aliases = " ".join(f"pr{n}: pullRequest(number: {n}) {{ ...F }}" for n in chunk)
        query = (
            f"query($owner: String!, $name: String!) {{ repository(owner: $owner, name: $name) {{ {aliases} }} }}"
            f" fragment F on PullRequest {{ {PR_FIELDS} }}"
        )
        data = graphql(query, owner=owner, name=name)["repository"]
        for number in chunk:
            pr = data.get(f"pr{number}")
            if pr is None:
                continue
            files = [f["path"] for f in pr["files"]["nodes"]]
            page = pr["files"]["pageInfo"]
            while page["hasNextPage"]:
                more = graphql(FILES_QUERY, owner=owner, name=name, number=number, cursor=page["endCursor"])
                more = more["repository"]["pullRequest"]["files"]
                files += [f["path"] for f in more["nodes"]]
                page = more["pageInfo"]
            yield pr_row(pr, files)
        print(f"fetched {min(start + batch, len(numbers))}/{len(numbers)} PRs", file=sys.stderr)


def pr_row(pr: dict, files: list[str]) -> dict:
    kind, scope, breaking, _ = parse_title(pr["title"])
    issues = [
        {
            "ref": f"{i['repository']['nameWithOwner']}#{i['number']}",
            "title": i["title"],
            "state": i["state"],
            "body": i["body"] or "",
            "comments": [
                {"author": (c["author"] or {}).get("login"), "created_at": c["createdAt"], "body": c["body"]}
                for c in i["comments"]["nodes"]
            ],
        }
        for i in pr["closingIssuesReferences"]["nodes"]
    ]
    return {
        "number": pr["number"],
        "title": pr["title"],
        "type": kind,
        "scope": scope,
        "breaking": breaking,
        "body": pr["body"] or "",
        "merged_at": pr["mergedAt"],
        "merge_commit": (pr["mergeCommit"] or {}).get("oid"),
        "head_commit": pr.get("headRefOid"),
        "author": (pr["author"] or {}).get("login"),
        "labels": [label["name"] for label in pr["labels"]["nodes"]],
        "files": sorted(set(files)),
        "issues": issues,
    }


def collect(root: Path, repo: str, numbers: list[int], rows: dict[int, dict]) -> None:
    for count, row in enumerate(fetch_prs(repo, numbers), 1):
        rows[row["number"]] = row
        if count % 50 == 0:
            save_dataset(root, rows)
    save_dataset(root, rows)


# Drift


def pr_section(body: str, name: str) -> str:
    body = re.sub(r"<!--.*?-->", "", body, flags=re.S)
    m = re.search(rf"^(#{{1,6}})\s*{re.escape(name)}\s*$", body, re.M | re.I)
    if not m:
        return ""
    end = re.compile(rf"^#{{1,{len(m.group(1))}}}\s", re.M).search(body, m.end())
    return re.sub(r"\n{3,}", "\n\n", body[m.end() : end.start() if end else len(body)]).strip()


def quote(text: str) -> list[str]:
    return [f"> {line}".rstrip() for line in text.splitlines()]


def render_drift(
    repo: str,
    base: str,
    head: str,
    commit_count: int,
    new_prs: list[tuple[dict, Assignment]],
    stale: dict[str, list[dict]],
    tree: Tree,
    scopes: Scopes,
    direct: list[tuple[str, str]],
) -> str:
    out = [
        "# Drift report",
        "",
        f"`{base[:7]}..{head[:7]}` on {repo}: {commit_count} commits, {len(new_prs)} PRs.",
        f"Once processed, set `watermark: {head}` in sources.yaml.",
        "",
        "## Affected features",
    ]
    if not stale:
        out += ["", "None."]
    for node_id in sorted(stale, key=id_key):
        node = tree.nodes[node_id]
        out += ["", f"### `{node_id}` — reviewed at `{node.reviewed_at()[:7]}`"]
        for row in sorted(stale[node_id], key=lambda r: r.get("merged_at") or ""):
            target = assign(tree, scopes, row).node
            placement = "History row here." if target == node_id else (
                f"Touches this feature; its row belongs on `{target}`." if target else "Touches this feature; in triage."
            )
            ref = f"{repo}#{row['number']}"
            out += ["", f"#### {ref} · {row['title']} · {(row.get('merged_at') or '')[:10]}", "", placement]
            if target == node_id:
                for name in ("Description", "How to test"):
                    text = pr_section(row.get("body") or "", name)
                    if text:
                        out += ["", f"**{name}**", ""] + quote(text)
    triage = [(row, a) for row, a in new_prs if a.node is None and not a.reason.startswith("ignored")]
    ignored = [(row, a) for row, a in new_prs if a.reason.startswith("ignored")]
    out += ["", "## Triage", ""]
    out += [
        f"- {repo}#{row['number']} · {row['title']} — {a.reason}. Files: "
        + ", ".join(f"`{f}`" for f in (row.get("files") or [])[:8])
        + (" …" if len(row.get("files") or []) > 8 else "")
        for row, a in triage
    ] or ["None."]
    out += ["", "## Ignored", ""]
    out += [f"- {repo}#{row['number']} · {row['title']}" for row, _ in ignored] or ["None."]
    out += ["", "## Commits without a PR", ""]
    out += [f"- `{sha[:7]}` {subject}" for sha, subject in direct] or ["None."]
    return "\n".join(out) + "\n"


# QA plans


def demote(text: str) -> list[str]:
    """A section's lines with its `###` groups turned into bold lines, for nesting under deeper headings."""
    return [f"**{line[4:].strip()}**" if line.startswith("### ") else line for line in text.splitlines()]


def run_lines(tree: Tree, nodes: list[str]) -> list[str]:
    tests = sorted({t for n in nodes for t in tree.nodes[n].listed("tests")})
    e2e = [t for t in tests if t.startswith(E2E_PREFIX)]
    rust = sorted({f for t in tests if (f := rust_filter(t))})
    rest = [t for t in tests if not t.startswith(E2E_PREFIX) and rust_filter(t) is None]
    out = []
    if e2e:
        out.append("- `./scripts/e2e.sh " + " ".join(e2e) + "`")
    if rust:
        filters = rust[0] if len(rust) == 1 else "-- " + " ".join(rust)
        out.append(f"- `./scripts/test-headless.py {filters}` (confirm the filter collected tests)")
    if rest:
        out.append("- Other tests: " + ", ".join(f"`{t}`" for t in rest))
    docs = sorted({d for n in nodes for d in tree.nodes[n].listed("docs") + inherited_docs(tree, n)})
    if docs:
        out.append("- Docs: " + ", ".join(f"`{d}`" for d in docs))
    return out or ["- No tests or docs are listed for these nodes."]


def role_text(radius: Radius | None, node_id: str) -> str:
    if radius is None:
        return "sweep"
    tier = radius.tier_of(node_id)
    if tier == 0:
        return "primary, owning node" if node_id == radius.owner else "primary"
    return f"regression, tier {tier}: {radius.why.get(node_id, TIERS.get(tier, ''))}"


def render_plan_sweep(tree: Tree, sweeps: Sweeps, area: str, nodes: list[str], radius: Radius | None) -> list[str]:
    sweep = sweeps.sweeps.get(area)
    area_nodes = [n for n in tree.ordered() if n.split("/")[0] == area]
    out = ["", f"## Sweep: {(sweep.meta.get('title') if sweep else None) or area} (`{area}`)", ""]
    if sweep:
        out.append(f"- Brief: `{sweep.path}`. Read its Scope and Setup before starting.")
        if sweep.listed("tools"):
            out.append("- Tools: " + ", ".join(f"`{t}`" for t in sweep.listed("tools")))
        if sweep.handoffs:
            out.append("- Also consider: " + "; ".join(f"{what} → `{t}`" for what, t in sweep.handoffs))
    else:
        out.append(f"- No sweep file yet; add `qa/sweeps/{area}.md`.")
    if not nodes:
        out.append("- Forced by a trigger: run the whole sweep. Its nodes are listed, not expanded.")
        out += ["", "Nodes: " + ", ".join(f"`{n}`" for n in area_nodes)]
    out += ["", "### Run first", ""] + run_lines(tree, nodes or area_nodes)
    if sweep and sweep.sections.get("Setup"):
        out += ["", "### Setup", ""] + demote(sweep.sections["Setup"])
    if sweep and sweep.probes.get(None):
        out += ["", "### Sweep-wide probes", ""] + [f"- {p}" for p in sweep.probes[None]]
    features: dict[str, list[str]] = {}
    for node_id in nodes:
        features.setdefault("/".join(node_id.split("/")[:2]), []).append(node_id)
    for feature, ids in features.items():
        out += ["", f"### Feature `{feature}`"]
        for node_id in ids:
            node = tree.nodes[node_id]
            out += ["", f"#### `{node_id}` — {node.meta.get('title') or node_id} ({role_text(radius, node_id)})", ""]
            behavior = node.sections.get("Behavior", "")
            out += demote(behavior) if behavior.strip() else ["No Behavior bullets of its own; see its children."]
            probes = sweep.probes.get(node_id) if sweep else None
            if probes:
                out += ["", "Probes:", ""] + [f"- {p}" for p in probes]
    return out


def render_plan(tree: Tree, sweeps: Sweeps, repo: str, plan: PlanInput) -> str:
    r = plan.radius
    out = [f"# QA plan: {plan.subject}", ""]
    out.append(f"- Head: `{plan.head}`" if plan.head else "- Head: unknown; resolve the commit under test first.")
    if plan.pr:
        pr_repo, number = plan.pr.get("ref", f"{repo}#{plan.pr['number']}").split("#")
        merged = plan.pr.get("merged_at")
        state = f"merged {merged[:10]}" if merged else "open"
        out.append(f"- PR: {ref_link(f'{pr_repo}#{number}')} · {state} · by {plan.pr.get('author') or 'unknown'}")
        issues = [i for i in plan.pr.get("issues") or [] if i.get("ref")]
        if issues:
            out.append("- Issues: " + ", ".join(f"{ref_link(i['ref'])} {i.get('title') or ''}".strip() for i in issues))
        out.append(
            f"- Checkout: `git -C <strata> fetch https://github.com/{pr_repo}.git pull/{number}/head:qa-{number} && "
            f"git -C <strata> worktree add ../strata-qa-{number} qa-{number}`"
        )
    if plan.files:
        shown = plan.files[:20]
        out.append(f"- Files: {len(plan.files)} changed")
        out += [f"  - `{f}`" for f in shown]
        if len(plan.files) > len(shown):
            out.append(f"  - … and {len(plan.files) - len(shown)} more")
    if r is not None:
        primary = [f"`{p}`" + (" (owning node)" if p == r.owner else "") for p in r.primary]
        out.append("- Primary: " + (", ".join(primary) or "none"))
        for tier, ids in r.tiers.items():
            note = "" if tier <= plan.tier else ", not expanded"
            out.append(f"- Tier {tier} ({TIERS[tier]}{note}): " + (", ".join(f"`{i}`" for i in ids) or "none"))
        if r.forced:
            out.append("- Forced sweeps:")
            out += [f"  - `{a}`: {'; '.join(w)}" for a, w in r.forced.items()]
        if r.unmapped:
            out.append(f"- Unmapped changes, no node or trigger: {len(r.unmapped)}")
            out += [f"  - `{f}`" for f in r.unmapped]
        nodes = r.nodes(plan.tier)
        reasons = launch(r, sweeps, plan.tier)
    else:
        nodes = [n for n in tree.ordered() if n.split("/")[0] in plan.areas]
        reasons = {a: ["requested"] for a in plan.areas}
    bullets = sum(len(tree.nodes[n].behavior) for n in nodes)
    out.append(f"- Size: {len(nodes)} nodes, {bullets} Behavior bullets")
    out += ["", "Read `qa/README.md` before launching. Reports are never committed to the feature map."]
    if plan.pr:
        for name in ("Description", "How to test"):
            text = pr_section(plan.pr.get("body") or "", name)
            if text:
                out += ["", f"## {name} (from the PR)", ""] + quote(text)
    if r is not None and r.primary:
        gaps = [(p, tree.nodes[p].sections.get("Known gaps", "")) for p in r.primary]
        gaps = [(p, text) for p, text in gaps if text and text != "None known."]
        if gaps:
            out += ["", "## Known gaps on primary nodes", "", "Already tracked; do not report these again."]
            for node_id, text in gaps:
                out += ["", f"### `{node_id}`", "", text]
    out += ["", "## Sweeps to launch", "", "| Sweep | Nodes | Why |", "| --- | --- | --- |"]
    per_sweep = {area: [n for n in nodes if n.split("/")[0] == area] for area in reasons}
    for area, why in reasons.items():
        out.append(f"| `{area}` | {len(per_sweep[area])} | {'; '.join(why)} |")
    for area in reasons:
        out += render_plan_sweep(tree, sweeps, area, per_sweep[area], r)
    return "\n".join(out) + "\n"


def parse_pr_ref(value: str, repo: str) -> tuple[str, int]:
    if value.isdigit():
        return repo, int(value)
    if re.fullmatch(REF, value):
        owner_repo, number = value.split("#")
        return owner_repo, int(number)
    raise SystemExit("--pr takes a number or owner/repo#n")


# Commands


def cmd_extract(args: argparse.Namespace) -> int:
    root = args.root
    upstream = load_sources(root)["upstream"]
    rows = load_dataset(root)
    numbers = merged_pr_numbers(upstream["repo"], upstream["branch"])
    todo = numbers if args.refresh else [n for n in numbers if n not in rows]
    collect(root, upstream["repo"], todo, rows)
    print(f"data/prs.jsonl: {len(rows)} PRs ({len(todo)} fetched, {len(numbers)} merged into {upstream['branch']})")
    return 0


def cmd_index(args: argparse.Namespace) -> int:
    written = write_index(args.root)
    print("index: " + (", ".join(written) if written else "up to date"))
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    lister = None if args.offline else Upstream(args.root, load_sources(args.root)).files
    issues = check(args.root, lister)
    for issue in issues:
        print(issue, file=sys.stderr)
    errors = sum(1 for i in issues if i.level == "error")
    counts = f"{len(load_tree(args.root).nodes)} features, {len(load_sweeps(args.root).sweeps)} sweeps"
    print(f"check: {counts}, {errors} errors, {len(issues) - errors} warnings")
    return 1 if errors else 0


def cmd_drift(args: argparse.Namespace) -> int:
    root = args.root
    sources = load_sources(root)
    repo = sources["upstream"]["repo"]
    base = args.since or sources.get("watermark")
    if not base:
        raise SystemExit("watermark is not set in sources.yaml; pass --since <sha> for a dry run")
    upstream = Upstream(root, sources)
    head = args.head or upstream.head()
    tree, scopes, dataset = load_tree(root), load_scopes(root), load_dataset(root)
    commits = upstream.log(base, head)
    numbers, direct = [], []
    for sha, subject in commits:
        m = PR_SUBJECT_RE.search(subject)
        if m:
            numbers.append(int(m.group(1) or m.group(2)))
        else:
            direct.append((sha, subject))
    missing = [n for n in numbers if n not in dataset]
    if missing:
        collect(root, repo, missing, dataset)
    new_prs = [(dataset[n], assign(tree, scopes, dataset[n])) for n in sorted(numbers) if n in dataset]
    stale: dict[str, list[dict]] = {}
    ranges: dict[str, set[str]] = {}
    for node_id, node in tree.nodes.items():
        sha = node.reviewed_at()
        if sha is None:
            continue
        if sha not in ranges:
            ranges[sha] = upstream.commits(sha, head)
        rows = [
            row
            for row in dataset.values()
            if row.get("merge_commit") in ranges[sha]
            and any(matches(p, f) for f in row.get("files") or [] for p in node.patterns())
        ]
        if rows:
            stale[node_id] = rows
    report = render_drift(repo, base, head, len(commits), new_prs, stale, tree, scopes, direct)
    if args.out:
        args.out.write_text(report)
    else:
        sys.stdout.write(report)
    return 0


def cmd_qa(args: argparse.Namespace) -> int:
    root = args.root
    sources = load_sources(root)
    upstream = sources.get("upstream") if isinstance(sources.get("upstream"), dict) else {}
    repo = upstream.get("repo", "lgse/strata")
    watermark = sources.get("watermark") if isinstance(sources.get("watermark"), str) else None
    tree, scopes, sweeps, dataset = load_tree(root), load_scopes(root), load_sweeps(root), load_dataset(root)
    if args.all or args.sweep:
        areas = sorted(sweeps.sweeps) if args.all else sorted(set(args.sweep))
        unknown = [a for a in areas if a not in sweeps.sweeps]
        if unknown:
            raise SystemExit("no such sweep: " + ", ".join(unknown))
        subject = "all sweeps" if args.all else "sweep " + ", ".join(f"`{a}`" for a in areas)
        plan = PlanInput(subject, args.head or watermark, None, [], None, areas, args.tier)
    else:
        pr, files, head = None, [], args.head
        if args.pr:
            pr_repo, number = parse_pr_ref(args.pr, repo)
            pr = dataset.get(number) if pr_repo == repo else None
            if pr is None:
                pr = next(fetch_prs(pr_repo, [number]), None)
            if pr is None:
                raise SystemExit(f"{pr_repo}#{number} was not found")
            pr = dict(pr, ref=f"{pr_repo}#{number}")
            files = pr.get("files") or []
            subject = f"{pr_repo}#{number} · {pr['title']}"
            head = head or pr.get("merge_commit") or pr.get("head_commit")
            owner = assign(tree, scopes, pr).node
            primary = sorted(touched(tree, files), key=id_key)
        elif args.files:
            text = sys.stdin.read() if args.files == "-" else Path(args.files).read_text()
            files = [line.strip() for line in text.splitlines() if line.strip()]
            subject = f"{len(files)} changed files"
            owner = assign(tree, scopes, {"files": files, "scope": None}).node
            primary = sorted(touched(tree, files), key=id_key)
        else:
            unknown = [n for n in args.node if n not in tree.nodes]
            if unknown:
                raise SystemExit("no such node: " + ", ".join(unknown))
            primary = sorted(set(args.node), key=id_key)
            subject = "node " + ", ".join(f"`{n}`" for n in primary)
            head = head or watermark
            owner = primary[0] if len(primary) == 1 else None
        reach = radius(tree, sweeps, primary, files, owner)
        if not reach.primary and not reach.forced:
            raise SystemExit("no node or trigger matches these files; nothing to plan:\n" + "\n".join(files))
        plan = PlanInput(subject, head, pr, files, reach, [], args.tier)
    text = render_plan(tree, sweeps, repo, plan)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text)
        print(f"qa: wrote {args.out}")
    else:
        sys.stdout.write(text)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT, help=argparse.SUPPRESS)
    sub = parser.add_subparsers(dest="command", required=True)
    extract = sub.add_parser("extract", help="pull merged upstream PRs into data/prs.jsonl")
    extract.add_argument("--refresh", action="store_true", help="refetch PRs already in the dataset")
    sub.add_parser("index", help="regenerate README.md and index/")
    check_cmd = sub.add_parser("check", help="validate the feature tree")
    check_cmd.add_argument("--offline", action="store_true", help="skip the upstream path check")
    drift = sub.add_parser("drift", help="report upstream changes since the watermark")
    drift.add_argument("--since", help="base commit instead of the watermark")
    drift.add_argument("--head", help="head commit instead of upstream's branch head")
    drift.add_argument("--out", type=Path, help="write the report here instead of stdout")
    qa = sub.add_parser("qa", help="render a QA plan for a PR, a diff, a node, or a sweep")
    what = qa.add_mutually_exclusive_group(required=True)
    what.add_argument("--pr", help="PR number, or owner/repo#n for a fork PR")
    what.add_argument("--files", help="file with one changed path per line, or - for stdin")
    what.add_argument("--node", action="append", help="node id; repeatable")
    what.add_argument("--sweep", action="append", help="sweep (area) name; repeatable")
    what.add_argument("--all", action="store_true", help="every sweep, for a full parallel run")
    qa.add_argument("--tier", type=int, choices=(1, 2, 3), default=2, help="how far the blast radius expands (default 2)")
    qa.add_argument("--head", help="commit under test, when the input does not imply one")
    qa.add_argument("--out", type=Path, help="write the plan here instead of stdout")
    args = parser.parse_args(argv)
    commands = {"extract": cmd_extract, "index": cmd_index, "check": cmd_check, "drift": cmd_drift, "qa": cmd_qa}
    return commands[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
