#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6"]
# ///
"""Build, validate, and sync the Strata feature map."""

from __future__ import annotations

import argparse
import functools
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SECTIONS = ("Summary", "Behavior", "Design", "History", "Known gaps")
STATUSES = ("proposed", "in-progress", "shipped", "deprecated", "removed")
REVIEWS = ("draft", "reviewed")
TYPES = ("feat", "fix", "perf", "refactor", "docs", "test", "build", "ci", "chore", "revert", "style")
REQUIRED = ("title", "status", "origin", "branch", "reviewed_at", "review", "code", "tests")
OPTIONAL = ("docs", "related")
LIST_FIELDS = ("code", "tests", "docs", "related")
MAX_DEPTH = 4
REF = r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+#\d+"
CITED_RE = re.compile(rf"\s{REF}(?:,\s*{REF})*(?:\s\(unverified\))?$")
SHA_RE = re.compile(r"[0-9a-f]{40}")
DATE_RE = re.compile(r"\d{4}-\d{2}-\d{2}")
TITLE_RE = re.compile(r"^(\w+)(?:\(([^)]*)\))?(!)?:\s*(.*)$")
PR_SUBJECT_RE = re.compile(r"\(#(\d+)\)$|^Merge pull request #(\d+)")
HISTORY_HEADER = ["Date", "PR", "Type", "Change"]
GENERATED = "<!-- Generated by scripts/featuremap.py index. Do not edit. -->"


@dataclass(frozen=True)
class Issue:
    level: str
    where: str
    message: str

    def __str__(self) -> str:
        return f"{self.level}: {self.where}: {self.message}"


@dataclass
class Node:
    id: str
    path: str
    meta: dict
    sections: dict[str, str]
    behavior: list[str] = field(default_factory=list)
    history: list[dict] = field(default_factory=list)

    @property
    def depth(self) -> int:
        return self.id.count("/") + 1

    def listed(self, key: str) -> list[str]:
        value = self.meta.get(key)
        return [v for v in value if isinstance(v, str)] if isinstance(value, list) else []

    def patterns(self) -> list[str]:
        return self.listed("code") + self.listed("tests")

    def reviewed_at(self) -> str | None:
        sha = self.meta.get("reviewed_at")
        return sha if isinstance(sha, str) and SHA_RE.fullmatch(sha) else None


@dataclass
class Tree:
    root: Path
    nodes: dict[str, Node]
    issues: list[Issue]

    def ordered(self) -> list[str]:
        return sorted(self.nodes, key=id_key)

    def subtree(self, node_id: str) -> list[str]:
        return [n for n in self.ordered() if n == node_id or n.startswith(node_id + "/")]

    def children(self, node_id: str) -> list[str]:
        return [n for n in self.subtree(node_id) if n.count("/") == node_id.count("/") + 1]

    def ancestors(self, node_id: str) -> list[str]:
        parts = node_id.split("/")
        candidates = ("/".join(parts[:i]) for i in range(2, len(parts)))
        return [c for c in candidates if c in self.nodes]


@dataclass
class Scopes:
    mapping: dict[str, str | None]
    ignore: set[str]


@dataclass
class Assignment:
    node: str | None
    reason: str
    affected: list[str]


def id_key(node_id: str) -> list[str]:
    return node_id.split("/")


def load_yaml(path: Path) -> dict:
    data = yaml.safe_load(path.read_text()) if path.exists() else None
    return data if isinstance(data, dict) else {}


def load_sources(root: Path) -> dict:
    return load_yaml(root / "sources.yaml")


def load_scopes(root: Path) -> Scopes:
    data = load_yaml(root / "scopes.yaml")
    mapping = {str(k): v for k, v in (data.get("scopes") or {}).items()}
    return Scopes(mapping, {str(s) for s in data.get("ignore") or []})


def load_dataset(root: Path) -> dict[int, dict]:
    path = root / "data" / "prs.jsonl"
    if not path.exists():
        return {}
    rows = (json.loads(line) for line in path.read_text().splitlines() if line.strip())
    return {row["number"]: row for row in rows}


def save_dataset(root: Path, rows: dict[int, dict]) -> None:
    path = root / "data" / "prs.jsonl"
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = (json.dumps(rows[n], ensure_ascii=False, sort_keys=True) + "\n" for n in sorted(rows))
    path.write_text("".join(lines))


@functools.lru_cache(maxsize=None)
def glob_regex(pattern: str) -> re.Pattern:
    """`*` stays within a directory, `**` crosses them; a plain path also matches what is under it."""
    if not any(c in pattern for c in "*?"):
        return re.compile(re.escape(pattern.rstrip("/")) + r"(?:/.*)?")
    out, i = [], 0
    while i < len(pattern):
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
        elif pattern.startswith("**", i):
            out.append(".*")
            i += 2
        elif pattern[i] == "*":
            out.append("[^/]*")
            i += 1
        elif pattern[i] == "?":
            out.append("[^/]")
            i += 1
        else:
            out.append(re.escape(pattern[i]))
            i += 1
    return re.compile("".join(out))


def matches(pattern: str, path: str) -> bool:
    return glob_regex(pattern).fullmatch(path) is not None


def parse_title(title: str) -> tuple[str | None, str | None, bool, str]:
    m = TITLE_RE.match(title)
    if not m:
        return None, None, False, title
    return m.group(1), m.group(2) or None, bool(m.group(3)), m.group(4)


# Parsing


def load_tree(root: Path) -> Tree:
    features = root / "features"
    tree = Tree(root, {}, [])
    if not features.is_dir():
        tree.issues.append(Issue("error", "features/", "directory is missing"))
        return tree
    for path in sorted(features.rglob("*")):
        parts = path.relative_to(features).parts
        rel = path.relative_to(root).as_posix()
        if any(p.startswith(".") for p in parts):
            continue
        if path.is_dir():
            if len(parts) >= 2 and not (path / "index.md").is_file():
                tree.issues.append(Issue("error", rel, "directory without index.md"))
            if len(parts) >= 2 and path.with_name(path.name + ".md").exists():
                tree.issues.append(Issue("error", rel, f"{path.name}.md and {path.name}/ both define one id"))
            continue
        if path.suffix != ".md":
            tree.issues.append(Issue("error", rel, "only Markdown files belong under features/"))
            continue
        if len(parts) == 1:
            tree.issues.append(Issue("error", rel, "areas are directories; no files directly under features/"))
            continue
        if len(parts) == 2 and parts[1] == "index.md":
            tree.issues.append(Issue("error", rel, "areas are directories only; an area has no index.md"))
            continue
        node_id = "/".join(parts[:-1]) if parts[-1] == "index.md" else "/".join(parts)[: -len(".md")]
        if node_id in tree.nodes:
            continue
        node, problems = parse_node(node_id, rel, path.read_text())
        tree.nodes[node_id] = node
        tree.issues.extend(Issue("error", rel, p) for p in problems)
        if node.depth > MAX_DEPTH:
            tree.issues.append(Issue("warning", rel, "deeper than area, feature, child, grandchild"))
    return tree


def parse_node(node_id: str, rel: str, text: str) -> tuple[Node, list[str]]:
    problems: list[str] = []
    meta: dict = {}
    body = text
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not m:
        problems.append("missing YAML front matter")
    else:
        body = text[m.end() :]
        try:
            loaded = yaml.safe_load(m.group(1))
        except yaml.YAMLError as e:
            problems.append(f"invalid front matter: {str(e).splitlines()[0]}")
            loaded = {}
        if isinstance(loaded, dict):
            meta = loaded
        else:
            problems.append("front matter must be a mapping")
        problems += validate_meta(meta)
    sections, section_problems = split_sections(body)
    problems += section_problems
    node = Node(node_id, rel, meta, sections)
    for name in ("Summary", "Design"):
        if name in sections and not sections[name]:
            problems.append(f"{name} is empty")
    if "Behavior" in sections:
        node.behavior, found = parse_behavior(sections["Behavior"])
        problems += found
    if "History" in sections:
        node.history, found = parse_history(sections["History"])
        problems += found
    if "Known gaps" in sections:
        problems += check_gaps(sections["Known gaps"])
    return node, problems


def validate_meta(meta: dict) -> list[str]:
    problems = [f"missing field '{k}'" for k in REQUIRED if k not in meta]
    for key in meta:
        if key == "id":
            problems.append("id is derived from the path; remove the id field")
        elif key not in REQUIRED + OPTIONAL:
            problems.append(f"unknown field '{key}'")
    title = meta.get("title")
    if "title" in meta and not (isinstance(title, str) and title.strip()):
        problems.append("title must be a non-empty string")
    status = meta.get("status")
    if "status" in meta and status not in STATUSES:
        problems.append(f"status must be one of {', '.join(STATUSES)}")
    if "review" in meta and meta["review"] not in REVIEWS:
        problems.append(f"review must be one of {', '.join(REVIEWS)}")
    sha = meta.get("reviewed_at")
    if "reviewed_at" in meta and not (isinstance(sha, str) and SHA_RE.fullmatch(sha)):
        problems.append("reviewed_at must be a full 40-character SHA, quoted if YAML reads it as a number")
    if "origin" in meta:
        problems += validate_origin(meta["origin"])
    branch = meta.get("branch")
    if status == "in-progress" and not (isinstance(branch, str) and branch.strip()):
        problems.append("branch is required while status is in-progress")
    if status != "in-progress" and branch is not None:
        problems.append("branch must be null unless status is in-progress")
    for key in LIST_FIELDS:
        value = meta.get(key, [])
        if not (isinstance(value, list) and all(isinstance(v, str) and v for v in value)):
            problems.append(f"{key} must be a list of non-empty strings")
    return problems


def validate_origin(origin: object) -> list[str]:
    if not isinstance(origin, dict) or set(origin) != {"issue", "pr"}:
        return ["origin must be {issue: <ref>|null, pr: <ref>|null}"]
    problems = []
    for key, value in origin.items():
        if value is not None and not (isinstance(value, str) and re.fullmatch(REF, value)):
            problems.append(f"origin.{key} must be owner/repo#n or null")
    if origin["issue"] is None and origin["pr"] is None:
        problems.append("origin needs an issue or a PR")
    return problems


def split_sections(body: str) -> tuple[dict[str, str], list[str]]:
    sections: dict[str, str] = {}
    order: list[str] = []
    problems: list[str] = []
    current: str | None = None
    lines: list[str] = []
    preamble: list[str] = []
    fenced = False
    for line in body.splitlines():
        if line.startswith("```"):
            fenced = not fenced
        if not fenced and line.startswith("# "):
            problems.append("no '#' title; the title lives in front matter")
            continue
        if not fenced and line.startswith("## "):
            if current is not None:
                sections[current] = "\n".join(lines).strip()
            current = line[3:].strip()
            order.append(current)
            lines = []
            continue
        (lines if current is not None else preamble).append(line)
    if current is not None:
        sections[current] = "\n".join(lines).strip()
    if any(line.strip() for line in preamble):
        problems.append("content before the first section")
    if order != list(SECTIONS):
        missing = [s for s in SECTIONS if s not in order]
        extra = [s for s in order if s not in SECTIONS]
        if missing:
            problems.append(f"missing section(s): {', '.join(missing)}")
        if extra:
            problems.append(f"unexpected section(s): {', '.join(extra)}")
        if not missing and not extra:
            problems.append(f"sections must appear once each, in order: {', '.join(SECTIONS)}")
    return sections, problems


def parse_bullets(text: str, section: str, subheadings: bool) -> tuple[list[str], list[str]]:
    bullets: list[str] = []
    problems: list[str] = []
    for line in text.splitlines():
        if not line.strip() or (subheadings and line.startswith("### ")):
            continue
        if line.startswith("- "):
            bullets.append(line[2:].strip())
        elif bullets and line.startswith("  ") and not line.lstrip().startswith(("- ", "* ")):
            bullets[-1] += " " + line.strip()
        else:
            allowed = "'- ' bullets and '###' subheadings" if subheadings else "'- ' bullets"
            problems.append(f"{section} allows only {allowed}: {line.strip()[:60]!r}")
    return bullets, problems


def parse_behavior(text: str) -> tuple[list[str], list[str]]:
    bullets, problems = parse_bullets(text, "Behavior", subheadings=True)
    for bullet in bullets:
        if not CITED_RE.search(" " + bullet):
            problems.append(f"Behavior bullet lacks a trailing citation: {bullet[:60]!r}")
    return bullets, problems


def parse_history(text: str) -> tuple[list[dict], list[str]]:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    if not lines or not all(line.startswith("|") and line.endswith("|") for line in lines):
        return [], ["History must be a single table"]
    cells = [[c.strip() for c in re.split(r"(?<!\\)\|", line[1:-1])] for line in lines]
    problems = []
    if cells[0] != HISTORY_HEADER:
        problems.append("History header must be | Date | PR | Type | Change |")
    if len(cells) < 2 or not all(re.fullmatch(r":?-+:?", c) for c in cells[1]):
        problems.append("History table is missing its separator row")
    rows = []
    for number, row in enumerate(cells[2:], 1):
        if len(row) != 4:
            problems.append(f"History row {number} needs 4 cells")
            continue
        date, pr, kind, change = row
        if not DATE_RE.fullmatch(date):
            problems.append(f"History row {number}: Date must be YYYY-MM-DD")
        if not re.fullmatch(REF, pr):
            problems.append(f"History row {number}: PR must be owner/repo#n")
        if kind.rstrip("!") not in TYPES:
            problems.append(f"History row {number}: Type must be one of {', '.join(TYPES)}")
        if not change:
            problems.append(f"History row {number}: Change is empty")
        rows.append({"date": date, "pr": pr, "type": kind, "change": change})
    dates = [r["date"] for r in rows]
    if dates != sorted(dates, reverse=True):
        problems.append("History must be newest first")
    seen = [r["pr"] for r in rows]
    for pr in sorted({p for p in seen if seen.count(p) > 1}):
        problems.append(f"History lists {pr} more than once")
    return rows, problems


def check_gaps(text: str) -> list[str]:
    if text == "None known.":
        return []
    bullets, problems = parse_bullets(text, "Known gaps", subheadings=False)
    if not bullets and not problems:
        return ["Known gaps is empty; write 'None known.'"]
    for bullet in bullets:
        if not re.search(REF, bullet):
            problems.append(f"Known gaps bullet must cite an issue: {bullet[:60]!r}")
    return problems


# Checking


def normalize(bullet: str) -> str:
    text = re.sub(rf"(?:,?\s*{REF})+(?:\s\(unverified\))?$", "", bullet)
    return " ".join(text.lower().split())


def check(root: Path, lister=None) -> list[Issue]:
    """`lister(sha)` returns upstream paths at that commit, or None if unknown. None skips the path check."""
    tree = load_tree(root)
    issues = list(tree.issues)
    sources = load_sources(root)
    scopes = load_scopes(root)
    if not isinstance(sources.get("upstream"), dict) or not sources["upstream"].get("repo"):
        issues.append(Issue("error", "sources.yaml", "upstream.repo is required"))
    watermark = sources.get("watermark")
    if watermark is not None and not (isinstance(watermark, str) and SHA_RE.fullmatch(watermark)):
        issues.append(Issue("error", "sources.yaml", "watermark must be null or a full 40-character SHA"))
    for scope, target in sorted(scopes.mapping.items()):
        if target is not None and target not in tree.nodes:
            issues.append(Issue("error", "scopes.yaml", f"scope '{scope}' maps to missing node '{target}'"))
        if scope in scopes.ignore:
            issues.append(Issue("error", "scopes.yaml", f"scope '{scope}' is both mapped and ignored"))
    for node_id in tree.ordered():
        node = tree.nodes[node_id]
        issues += [Issue("error", node.path, m) for m in tree_problems(tree, node)]
        if lister is not None:
            issues += [Issue("error", node.path, m) for m in path_problems(node, lister)]
    if not any(i.level == "error" and i.where.startswith("features") for i in issues):
        stale = [p for p, text in render_index(tree, sources, load_dataset(root)).items() if read(root / p) != text]
        if stale:
            issues.append(Issue("error", ", ".join(stale), "stale index; run featuremap.py index"))
    return issues


def tree_problems(tree: Tree, node: Node) -> list[str]:
    problems = []
    for related in node.listed("related"):
        if related == node.id:
            problems.append("related lists the node itself")
        elif related not in tree.nodes:
            problems.append(f"related id '{related}' does not exist")
    ancestors = tree.ancestors(node.id)
    own = {normalize(b) for b in node.behavior}
    for ancestor in ancestors:
        for bullet in tree.nodes[ancestor].behavior:
            if normalize(bullet) in own:
                problems.append(f"Behavior bullet also in ancestor {ancestor}: {bullet[:60]!r}")
        prs = {r["pr"] for r in tree.nodes[ancestor].history}
        for row in node.history:
            if row["pr"] in prs:
                problems.append(f"{row['pr']} also has a History row on ancestor {ancestor}")
    if node.meta.get("status") == "shipped" and not node.behavior and not tree.children(node.id):
        problems.append("a shipped leaf needs Behavior bullets")
    return problems


def path_problems(node: Node, lister) -> list[str]:
    sha = node.reviewed_at()
    if sha is None:
        return []
    files = lister(sha)
    if files is None:
        return [f"reviewed_at {sha[:7]} is not an upstream commit"]
    return [
        f"{key} entry {pattern!r} matches nothing upstream at {sha[:7]}"
        for key in ("code", "tests", "docs")
        for pattern in node.listed(key)
        if not any(matches(pattern, f) for f in files)
    ]


def read(path: Path) -> str | None:
    return path.read_text() if path.exists() else None


# Mapping


def touched(tree: Tree, files: list[str]) -> dict[str, int]:
    hits = {}
    for node_id, node in tree.nodes.items():
        count = sum(1 for f in files if any(matches(p, f) for p in node.patterns()))
        if count:
            hits[node_id] = count
    return hits


def common_prefix(ids: list[str]) -> str:
    common = []
    for segments in zip(*(i.split("/") for i in ids)):
        if len(set(segments)) != 1:
            break
        common.append(segments[0])
    return "/".join(common)


def assign(tree: Tree, scopes: Scopes, pr: dict) -> Assignment:
    """Scope picks the subtree, touched paths pick the most specific node in it."""
    hits = touched(tree, pr.get("files") or [])
    affected = sorted(hits, key=id_key)
    scope = pr.get("scope")
    if scope in scopes.ignore:
        return Assignment(None, f"ignored scope '{scope}'", affected)
    target = scopes.mapping.get(scope) if scope else None
    if target and target not in tree.nodes:
        return Assignment(None, f"scope '{scope}' maps to missing node '{target}'", affected)
    pool = [n for n in affected if not target or n == target or n.startswith(target + "/")]
    leaves = [n for n in pool if not any(o.startswith(n + "/") for o in pool)]
    if len(leaves) == 1:
        return Assignment(leaves[0], "scope and paths" if target else "paths", affected)
    if leaves:
        shared = common_prefix(leaves)
        if shared in tree.nodes:
            return Assignment(shared, "paths span its children", affected)
        if target:
            return Assignment(target, f"scope '{scope}'; paths span several children", affected)
        return Assignment(None, "touches several features: " + ", ".join(leaves), affected)
    if target:
        return Assignment(target, f"scope '{scope}'", affected)
    return Assignment(None, f"scope '{scope}' is unmapped" if scope else "no scope and no matching paths", affected)


# Indexes


def render_index(tree: Tree, sources: dict, dataset: dict[int, dict]) -> dict[str, str]:
    upstream = sources.get("upstream") if isinstance(sources.get("upstream"), dict) else {}
    repo = upstream.get("repo", "lgse/strata")
    since = {n: changes_since(tree, n, dataset) for n in tree.ordered()}
    return {
        "README.md": render_readme(tree, repo, sources.get("watermark"), since),
        "index/by-area.md": render_by_area(tree, repo, since),
        "index/by-path.md": render_by_path(tree),
        "index/by-pr.md": render_by_pr(tree),
    }


def changes_since(tree: Tree, node_id: str, dataset: dict[int, dict]) -> str:
    """PRs touching the subtree merged after its oldest review; '?' when a review commit is not in the dataset."""
    merged = {row.get("merge_commit"): row.get("merged_at") for row in dataset.values()}
    subtree = [tree.nodes[n] for n in tree.subtree(node_id)]
    dates = [merged.get(n.reviewed_at()) for n in subtree]
    if not dataset or any(d is None for d in dates):
        return "?"
    oldest = min(dates)
    patterns = [p for n in subtree for p in n.patterns()]
    count = sum(
        1
        for row in dataset.values()
        if (row.get("merged_at") or "") > oldest
        and any(matches(p, f) for f in row.get("files") or [] for p in patterns)
    )
    return str(count)


def ref_link(ref: str) -> str:
    repo, number = ref.split("#")
    return f"[{ref}](https://github.com/{repo}/issues/{number})"


def path_link(repo: str, sha: str | None, pattern: str) -> str:
    rev = sha or "HEAD"
    if not any(c in pattern for c in "*?"):
        return f"[`{pattern}`](https://github.com/{repo}/blob/{rev}/{pattern})"
    static = []
    for segment in pattern.split("/"):
        if any(c in segment for c in "*?"):
            break
        static.append(segment)
    return f"[`{pattern}`](https://github.com/{repo}/tree/{rev}/{'/'.join(static)})"


def node_link(tree: Tree, node_id: str, prefix: str = "") -> str:
    node = tree.nodes[node_id]
    return f"[{node.meta.get('title') or node_id}]({prefix}{node.path})"


def render_readme(tree: Tree, repo: str, watermark: object, since: dict[str, str]) -> str:
    reviewed = sum(1 for n in tree.nodes.values() if n.meta.get("review") == "reviewed")
    mark = f"`{watermark[:7]}`" if isinstance(watermark, str) else "not set"
    out = [
        GENERATED,
        "",
        "# Strata feature map",
        "",
        "One Markdown file per Strata feature, tying shipped behavior and design to the upstream issues and "
        "PRs that produced it. [AGENTS.md](AGENTS.md) holds the schema and the rules for editing it.",
        "",
        "Look features up [by area](index/by-area.md), [by path](index/by-path.md), or [by PR](index/by-pr.md). "
        "*PRs since* counts upstream PRs touching a feature or its children since the oldest review in its "
        "subtree; `?` means the review commit is not in `data/prs.jsonl` yet.",
        "",
        f"Upstream [{repo}](https://github.com/{repo}) · watermark {mark} · "
        f"{len(tree.nodes)} features, {reviewed} reviewed",
    ]
    areas = sorted({n.split("/")[0] for n in tree.nodes})
    if not areas:
        out += ["", "No features yet."]
    for area in areas:
        out += ["", f"## {area}", "", "| Feature | Id | Status | Review | Reviewed at | PRs since |"]
        out.append("| --- | --- | --- | --- | --- | --- |")
        for node_id in [n for n in tree.ordered() if n.split("/")[0] == area]:
            node = tree.nodes[node_id]
            indent = "&emsp;" * (node.depth - 3) + "↳ " if node.depth > 2 else ""
            sha = node.reviewed_at()
            out.append(
                f"| {indent}{node_link(tree, node_id)} | `{node_id}` | {node.meta.get('status')} | "
                f"{node.meta.get('review')} | {f'`{sha[:7]}`' if sha else '—'} | {since[node_id]} |"
            )
    return "\n".join(out) + "\n"


def render_by_area(tree: Tree, repo: str, since: dict[str, str]) -> str:
    out = [GENERATED, "", "# Features by area"]
    area = None
    for node_id in tree.ordered():
        node = tree.nodes[node_id]
        if node_id.split("/")[0] != area:
            area = node_id.split("/")[0]
            out += ["", f"## {area}"]
        sha = node.reviewed_at()
        reviewed = f"reviewed at [`{sha[:7]}`](https://github.com/{repo}/tree/{sha})" if sha else "not reviewed"
        out += [
            "",
            f"### {node_link(tree, node_id, '../')} `{node_id}`",
            "",
            f"{node.meta.get('status')} · {node.meta.get('review')} · {reviewed} · {since[node_id]} PRs since",
        ]
        origin = node.meta.get("origin") if isinstance(node.meta.get("origin"), dict) else {}
        refs = [f"{k} {ref_link(v)}" for k, v in origin.items() if isinstance(v, str) and re.fullmatch(REF, v)]
        if refs:
            out[-1] += " · origin " + ", ".join(refs)
        if node.sections.get("Summary"):
            out += ["", node.sections["Summary"]]
        inherited = [d for a in tree.ancestors(node_id) for d in tree.nodes[a].listed("docs")]
        rows = [
            ("Code", [path_link(repo, sha, p) for p in node.listed("code")]),
            ("Tests", [path_link(repo, sha, p) for p in node.listed("tests")]),
            ("Docs", [path_link(repo, sha, p) for p in node.listed("docs")]
             + [path_link(repo, sha, p) + " (inherited)" for p in inherited]),
            ("Related", [node_link(tree, r, "../") for r in node.listed("related") if r in tree.nodes]),
            ("Children", [node_link(tree, c, "../") for c in tree.children(node_id)]),
        ]
        items = [f"- {label}: {', '.join(values)}" for label, values in rows if values]
        if items:
            out += [""] + items
    if not tree.nodes:
        out += ["", "No features yet."]
    return "\n".join(out) + "\n"


def render_by_path(tree: Tree) -> str:
    out = [
        GENERATED,
        "",
        "# Features by path",
        "",
        "Each upstream path or glob with the node that owns it and that node's ancestors, which share its coverage.",
        "",
        "| Path | Kind | Node | Ancestors |",
        "| --- | --- | --- | --- |",
    ]
    rows = sorted(
        (pattern, kind, node_id)
        for node_id, node in tree.nodes.items()
        for kind in ("code", "tests")
        for pattern in node.listed(kind)
    )
    for pattern, kind, node_id in rows:
        ancestors = ", ".join(node_link(tree, a, "../") for a in reversed(tree.ancestors(node_id))) or "—"
        out.append(f"| `{pattern}` | {kind} | {node_link(tree, node_id, '../')} | {ancestors} |")
    return "\n".join(out) + "\n"


def render_by_pr(tree: Tree) -> str:
    out = [
        GENERATED,
        "",
        "# Features by PR",
        "",
        "Every History row across the tree, newest first.",
        "",
        "| PR | Date | Type | Node | Change |",
        "| --- | --- | --- | --- | --- |",
    ]
    rows = [(r, node_id) for node_id, node in tree.nodes.items() for r in node.history]
    rows.sort(key=lambda item: (item[0]["date"], int(item[0]["pr"].split("#")[1]), item[1]), reverse=True)
    for row, node_id in rows:
        out.append(
            f"| {ref_link(row['pr'])} | {row['date']} | {row['type']} | {node_link(tree, node_id, '../')} | "
            f"{row['change']} |"
        )
    return "\n".join(out) + "\n"


def write_index(root: Path) -> list[str]:
    tree = load_tree(root)
    written = []
    for rel, text in render_index(tree, load_sources(root), load_dataset(root)).items():
        path = root / rel
        if read(path) != text:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            written.append(rel)
    return written


# Upstream access


class Upstream:
    """A blobless bare clone of upstream in .cache/, or a read-only clone named by FEATUREMAP_UPSTREAM."""

    def __init__(self, root: Path, sources: dict):
        upstream = sources.get("upstream") or {}
        self.repo = upstream.get("repo", "lgse/strata")
        self.branch = upstream.get("branch", "main")
        configured = os.environ.get("FEATUREMAP_UPSTREAM")
        self.managed = configured is None
        self.git_dir = Path(configured) if configured else root / ".cache" / "upstream.git"
        self.ref = os.environ.get("FEATUREMAP_UPSTREAM_REF") or f"refs/heads/{self.branch}"
        self.synced = False
        self.trees: dict[str, set[str] | None] = {}

    def git(self, *args: str) -> str:
        result = subprocess.run(["git", "-C", str(self.git_dir), *args], capture_output=True, text=True)
        if result.returncode:
            raise SystemExit(f"git {' '.join(args)} failed: {result.stderr.strip()}")
        return result.stdout

    def sync(self) -> None:
        if not self.managed or self.synced:
            return
        self.synced = True
        if not self.git_dir.exists():
            self.git_dir.parent.mkdir(parents=True, exist_ok=True)
            url = f"https://github.com/{self.repo}.git"
            subprocess.run(["git", "clone", "--quiet", "--bare", "--filter=blob:none", url, str(self.git_dir)], check=True)
        else:
            self.git("fetch", "--quiet", "--filter=blob:none", "origin", f"+refs/heads/{self.branch}:refs/heads/{self.branch}")

    def has(self, sha: str) -> bool:
        if not self.git_dir.exists():
            return False
        probe = ["git", "-C", str(self.git_dir), "cat-file", "-e", f"{sha}^{{commit}}"]
        return subprocess.run(probe, capture_output=True).returncode == 0

    def files(self, sha: str) -> set[str] | None:
        if sha not in self.trees:
            if not self.has(sha):
                self.sync()
            self.trees[sha] = set(self.git("ls-tree", "-r", "--name-only", sha).splitlines()) if self.has(sha) else None
        return self.trees[sha]

    def head(self) -> str:
        self.sync()
        return self.git("rev-parse", self.ref).strip()

    def log(self, base: str, head: str) -> list[tuple[str, str]]:
        out = self.git("log", "--first-parent", "--format=%H%x09%s", f"{base}..{head}")
        return [tuple(line.split("\t", 1)) for line in out.splitlines()]

    def commits(self, base: str, head: str) -> set[str]:
        return set(self.git("rev-list", "--first-parent", f"{base}..{head}").split())


# GitHub access

LIST_QUERY = """
query($owner: String!, $name: String!, $base: String!, $cursor: String) {
  repository(owner: $owner, name: $name) {
    pullRequests(states: MERGED, baseRefName: $base, first: 100, after: $cursor,
                 orderBy: {field: CREATED_AT, direction: ASC}) {
      pageInfo { hasNextPage endCursor }
      nodes { number }
    }
  }
}"""

PR_FIELDS = """
  number title body mergedAt
  mergeCommit { oid }
  author { login }
  labels(first: 20) { nodes { name } }
  files(first: 100) { pageInfo { hasNextPage endCursor } nodes { path } }
  closingIssuesReferences(first: 10) {
    nodes {
      number title state body repository { nameWithOwner }
      comments(first: 100) { nodes { author { login } createdAt body } }
    }
  }"""

FILES_QUERY = """
query($owner: String!, $name: String!, $number: Int!, $cursor: String) {
  repository(owner: $owner, name: $name) {
    pullRequest(number: $number) {
      files(first: 100, after: $cursor) { pageInfo { hasNextPage endCursor } nodes { path } }
    }
  }
}"""


def graphql(query: str, **variables: object) -> dict:
    args = ["gh", "api", "graphql", "-f", f"query={query}"]
    for key, value in variables.items():
        args += ["-F" if isinstance(value, int) else "-f", f"{key}={value}"]
    result = subprocess.run(args, capture_output=True, text=True)
    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError:
        raise SystemExit(f"gh api graphql failed: {result.stderr.strip()}")
    if result.returncode or data.get("errors"):
        raise SystemExit(f"gh api graphql failed: {data.get('errors') or result.stderr.strip()}")
    return data["data"]


def merged_pr_numbers(repo: str, branch: str) -> list[int]:
    owner, name = repo.split("/")
    numbers: list[int] = []
    cursor = None
    while True:
        variables = {"owner": owner, "name": name, "base": branch} | ({"cursor": cursor} if cursor else {})
        page = graphql(LIST_QUERY, **variables)["repository"]["pullRequests"]
        numbers += [n["number"] for n in page["nodes"]]
        if not page["pageInfo"]["hasNextPage"]:
            return numbers
        cursor = page["pageInfo"]["endCursor"]


def fetch_prs(repo: str, numbers: list[int], batch: int = 10):
    owner, name = repo.split("/")
    for start in range(0, len(numbers), batch):
        chunk = numbers[start : start + batch]
        aliases = " ".join(f"pr{n}: pullRequest(number: {n}) {{ ...F }}" for n in chunk)
        query = (
            f"query($owner: String!, $name: String!) {{ repository(owner: $owner, name: $name) {{ {aliases} }} }}"
            f" fragment F on PullRequest {{ {PR_FIELDS} }}"
        )
        data = graphql(query, owner=owner, name=name)["repository"]
        for number in chunk:
            pr = data.get(f"pr{number}")
            if pr is None:
                continue
            files = [f["path"] for f in pr["files"]["nodes"]]
            page = pr["files"]["pageInfo"]
            while page["hasNextPage"]:
                more = graphql(FILES_QUERY, owner=owner, name=name, number=number, cursor=page["endCursor"])
                more = more["repository"]["pullRequest"]["files"]
                files += [f["path"] for f in more["nodes"]]
                page = more["pageInfo"]
            yield pr_row(pr, files)
        print(f"fetched {min(start + batch, len(numbers))}/{len(numbers)} PRs", file=sys.stderr)


def pr_row(pr: dict, files: list[str]) -> dict:
    kind, scope, breaking, _ = parse_title(pr["title"])
    issues = [
        {
            "ref": f"{i['repository']['nameWithOwner']}#{i['number']}",
            "title": i["title"],
            "state": i["state"],
            "body": i["body"] or "",
            "comments": [
                {"author": (c["author"] or {}).get("login"), "created_at": c["createdAt"], "body": c["body"]}
                for c in i["comments"]["nodes"]
            ],
        }
        for i in pr["closingIssuesReferences"]["nodes"]
    ]
    return {
        "number": pr["number"],
        "title": pr["title"],
        "type": kind,
        "scope": scope,
        "breaking": breaking,
        "body": pr["body"] or "",
        "merged_at": pr["mergedAt"],
        "merge_commit": (pr["mergeCommit"] or {}).get("oid"),
        "author": (pr["author"] or {}).get("login"),
        "labels": [label["name"] for label in pr["labels"]["nodes"]],
        "files": sorted(set(files)),
        "issues": issues,
    }


def collect(root: Path, repo: str, numbers: list[int], rows: dict[int, dict]) -> None:
    for count, row in enumerate(fetch_prs(repo, numbers), 1):
        rows[row["number"]] = row
        if count % 50 == 0:
            save_dataset(root, rows)
    save_dataset(root, rows)


# Drift


def pr_section(body: str, name: str) -> str:
    body = re.sub(r"<!--.*?-->", "", body, flags=re.S)
    m = re.search(rf"^(#{{1,6}})\s*{re.escape(name)}\s*$", body, re.M | re.I)
    if not m:
        return ""
    end = re.compile(rf"^#{{1,{len(m.group(1))}}}\s", re.M).search(body, m.end())
    return re.sub(r"\n{3,}", "\n\n", body[m.end() : end.start() if end else len(body)]).strip()


def quote(text: str) -> list[str]:
    return [f"> {line}".rstrip() for line in text.splitlines()]


def render_drift(
    repo: str,
    base: str,
    head: str,
    commit_count: int,
    new_prs: list[tuple[dict, Assignment]],
    stale: dict[str, list[dict]],
    tree: Tree,
    scopes: Scopes,
    direct: list[tuple[str, str]],
) -> str:
    out = [
        "# Drift report",
        "",
        f"`{base[:7]}..{head[:7]}` on {repo}: {commit_count} commits, {len(new_prs)} PRs.",
        f"Once processed, set `watermark: {head}` in sources.yaml.",
        "",
        "## Affected features",
    ]
    if not stale:
        out += ["", "None."]
    for node_id in sorted(stale, key=id_key):
        node = tree.nodes[node_id]
        out += ["", f"### `{node_id}` — reviewed at `{node.reviewed_at()[:7]}`"]
        for row in sorted(stale[node_id], key=lambda r: r.get("merged_at") or ""):
            target = assign(tree, scopes, row).node
            placement = "History row here." if target == node_id else (
                f"Touches this feature; its row belongs on `{target}`." if target else "Touches this feature; in triage."
            )
            ref = f"{repo}#{row['number']}"
            out += ["", f"#### {ref} · {row['title']} · {(row.get('merged_at') or '')[:10]}", "", placement]
            if target == node_id:
                for name in ("Description", "How to test"):
                    text = pr_section(row.get("body") or "", name)
                    if text:
                        out += ["", f"**{name}**", ""] + quote(text)
    triage = [(row, a) for row, a in new_prs if a.node is None and not a.reason.startswith("ignored")]
    ignored = [(row, a) for row, a in new_prs if a.reason.startswith("ignored")]
    out += ["", "## Triage", ""]
    out += [
        f"- {repo}#{row['number']} · {row['title']} — {a.reason}. Files: "
        + ", ".join(f"`{f}`" for f in (row.get("files") or [])[:8])
        + (" …" if len(row.get("files") or []) > 8 else "")
        for row, a in triage
    ] or ["None."]
    out += ["", "## Ignored", ""]
    out += [f"- {repo}#{row['number']} · {row['title']}" for row, _ in ignored] or ["None."]
    out += ["", "## Commits without a PR", ""]
    out += [f"- `{sha[:7]}` {subject}" for sha, subject in direct] or ["None."]
    return "\n".join(out) + "\n"


# Commands


def cmd_extract(args: argparse.Namespace) -> int:
    root = args.root
    upstream = load_sources(root)["upstream"]
    rows = load_dataset(root)
    numbers = merged_pr_numbers(upstream["repo"], upstream["branch"])
    todo = numbers if args.refresh else [n for n in numbers if n not in rows]
    collect(root, upstream["repo"], todo, rows)
    print(f"data/prs.jsonl: {len(rows)} PRs ({len(todo)} fetched, {len(numbers)} merged into {upstream['branch']})")
    return 0


def cmd_index(args: argparse.Namespace) -> int:
    written = write_index(args.root)
    print("index: " + (", ".join(written) if written else "up to date"))
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    lister = None if args.offline else Upstream(args.root, load_sources(args.root)).files
    issues = check(args.root, lister)
    for issue in issues:
        print(issue, file=sys.stderr)
    errors = sum(1 for i in issues if i.level == "error")
    print(f"check: {len(load_tree(args.root).nodes)} features, {errors} errors, {len(issues) - errors} warnings")
    return 1 if errors else 0


def cmd_drift(args: argparse.Namespace) -> int:
    root = args.root
    sources = load_sources(root)
    repo = sources["upstream"]["repo"]
    base = args.since or sources.get("watermark")
    if not base:
        raise SystemExit("watermark is not set in sources.yaml; pass --since <sha> for a dry run")
    upstream = Upstream(root, sources)
    head = args.head or upstream.head()
    tree, scopes, dataset = load_tree(root), load_scopes(root), load_dataset(root)
    commits = upstream.log(base, head)
    numbers, direct = [], []
    for sha, subject in commits:
        m = PR_SUBJECT_RE.search(subject)
        if m:
            numbers.append(int(m.group(1) or m.group(2)))
        else:
            direct.append((sha, subject))
    missing = [n for n in numbers if n not in dataset]
    if missing:
        collect(root, repo, missing, dataset)
    new_prs = [(dataset[n], assign(tree, scopes, dataset[n])) for n in sorted(numbers) if n in dataset]
    stale: dict[str, list[dict]] = {}
    ranges: dict[str, set[str]] = {}
    for node_id, node in tree.nodes.items():
        sha = node.reviewed_at()
        if sha is None:
            continue
        if sha not in ranges:
            ranges[sha] = upstream.commits(sha, head)
        rows = [
            row
            for row in dataset.values()
            if row.get("merge_commit") in ranges[sha]
            and any(matches(p, f) for f in row.get("files") or [] for p in node.patterns())
        ]
        if rows:
            stale[node_id] = rows
    report = render_drift(repo, base, head, len(commits), new_prs, stale, tree, scopes, direct)
    if args.out:
        args.out.write_text(report)
    else:
        sys.stdout.write(report)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT, help=argparse.SUPPRESS)
    sub = parser.add_subparsers(dest="command", required=True)
    extract = sub.add_parser("extract", help="pull merged upstream PRs into data/prs.jsonl")
    extract.add_argument("--refresh", action="store_true", help="refetch PRs already in the dataset")
    sub.add_parser("index", help="regenerate README.md and index/")
    check_cmd = sub.add_parser("check", help="validate the feature tree")
    check_cmd.add_argument("--offline", action="store_true", help="skip the upstream path check")
    drift = sub.add_parser("drift", help="report upstream changes since the watermark")
    drift.add_argument("--since", help="base commit instead of the watermark")
    drift.add_argument("--head", help="head commit instead of upstream's branch head")
    drift.add_argument("--out", type=Path, help="write the report here instead of stdout")
    args = parser.parse_args(argv)
    commands = {"extract": cmd_extract, "index": cmd_index, "check": cmd_check, "drift": cmd_drift}
    return commands[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
